### ISSUE TITLE
In Express middleware, call next when match is not found

### ISSUE THREAD

**Issue by Satyam** [Hashnode/mern-starter#101]
In:

https://github.com/Hashnode/mern-starter/blob/master/server/server.js#L86

When the route is not found, instead of sending a 404 Not Found message, `next()` should be called.  `next` is the third parameter in `app.use(req, res, next)`.   In this case, this would not be necessary,as there is no further middleware after it, but it would still be good manners to do it, just in case.  Otherwise, this can only be the last middleware to be processed.

Express already sends the 404 message when no match is found and there are no further middleware to be tried.

**Comment by SOSANA** [comment]
@Satyam do a PR, good catch!
