### ISSUE TITLE
adding nodemon to mern-starter

### ISSUE THREAD

**Issue by SOSANA** [Hashnode/mern-starter#109]
Hey guys,

Can you do a PR adding this? I know we tried including it in other PR's but thought we should add it on its own unless you have reasons not too.

Also noticed that nodemon.json was not included in previous PR's, Thinking we include this in case nodemon is not installed globally.

curious your thoughts @prank7 @sandeeppanda92 @mayankchd @carloscuatin

**Comment by mayankchd** [comment]
Send a PR @SOSANA!

**Comment by carloscuatin** [comment]
@SOSANA @mayankchd sending a pr

**Comment by SOSANA** [comment]
@carloscuatin @mayankchd epic bro!!!

**Comment by SOSANA** [comment]
@mayankchd @carloscuatin any chance we can squeeze in minor update to server.js I forgot to include in #108 ?

upon init in redux we provide unneeded post {}

update needed on line 100
from `const initialState = { posts: [], post: {} };` to `const initialState = { posts: [] };`

or do seperate pr?

**Comment by SOSANA** [comment]
disregard last comment about removing post {}

**Comment by SOSANA** [comment]
@carloscuatin you stil going to do a PR for this? :)

**Comment by carloscuatin** [comment]
@SOSANA PR #117

**Comment by carloscuatin** [comment]
@SOSANA close issue
