### ISSUE TITLE
CSS Modules Support and usage in the example code

### ISSUE THREAD

**Issue by Ajar-Ajar** [Hashnode/mern-starter#115]
Mern implements the nessecary configuration for CSS modules, but for some reason is not doing any use of it in the starter example code... all the css exists in one big monolithic file and all the css selectors are globally scoped just like traditional regular css.
The reason to implement CSS Modules to begin with is to be able to have locally scoped styles, nicely packed for each module. Next to each view, in the same folder needs to exist a styles.css with the local styles. 
While not a part of the example code, if you simply add styles.css next to every view, it will actually work!
or should I say - it works as long as you are using the Dev configuration and creating a lot of inline style tags in your html as a result... When you actually try to use the text extraction webpack plugin for production all the CSS Modules styles are gone and the only styles which are being computed are the ones written in the css file under the static folder... :( 
So yes - we need a full css modules solution that works in production as well...
I also wasn't able to figure out how to implement sass into this css modules workflow. I installed sass-loader and followed the documentation of CSS Modules for sass and nothing actually happens :(
If anyone had any luck with it, i'd appreciate any help. last thing you want is writing all your styles in one globally scoped file...
Cheers
Ajar

**Comment by Ajar-Ajar** [comment]
I've been checking out postcss and It looks like it is picking up in momentum. It blends into the webpack and CSS Modules much more smoothly. it has all the advantages sass gives you and tones more, and it's all in javascript!
So I have to vote for postcss and advise everyone here to check it out in depth.

**Comment by somus** [comment]
@Ajar-Ajar You are right. The whole css in a single file is not good. We need CSS modules. I'm not sure whether we can use just PostCSS or SASS or both. We can continue the discussion at #89.
