### ISSUE TITLE
Adding auth with passport.js?

### ISSUE THREAD

**Issue by sirrodgepodge** [Hashnode/mern-starter#116]
Yo dudes!  

I think I've come up with a pretty nifty way to add auth, was a bit of a challenge to use passport.js isomorphically, do you think this still fits with a "starter" application?

I think it's pretty common to want this.  If you guys think it should be included I'll make a PR.

**Comment by SOSANA** [comment]
@sirrodgepodge I am down bro!!! you have a forked copy to checkout?

@prank7 @mayankchd @sandeeppanda92 thoughts?

**Comment by carloscuatin** [comment]
@sirrodgepodge to me in particular I prefer an implementation of JWT depending on the context where such run localStorage to save the token etc.

**Comment by sirrodgepodge** [comment]
Haha thanks for the enthusiasm Sosana.

Carlos,

I do hear that JWT is what all the cool kids are doing these days, I haven't explored it yet.

I've used passport.js a bunch, haven't seen a good example of someone using JWT for third party auth (Google, Facebook, etc.) though from what I understand it's really good at that actually.

Do you have a nice learning example to point to?

**Comment by SOSANA** [comment]
@sirrodgepodge Thanks mango!

I'm with @carloscuatin  I'd like to work with JWT more and see a good implementation of it. Was hoping to getting around to doing it one of these weekends for my own curiosity. At the end of the day this might not be in the plans but we need feed back from @prank7 @mayankchd @sandeeppanda92 about having a working example. 

I think would be wise to focus our attention on mern-cli and how we could implement new features as options. Maybe this is one of them? simply select the options upon scaffolding (JWT, postcss implementation, or  in future scaffolding server routes/controllers/models or shared component/redux reducers/actions/etc),

**Comment by prank7** [comment]
@sirrodgepodge, @SOSANA has a good point. We would like to have a way to add authentication but that should be conditionally through mern-cli i.e. if you do something like this `mern newApp --with-auth', it should generate the relevant templates.

**Comment by Ajar-Ajar** [comment]
+1 for JWT rather then passport. Better not having a user session at scale...
Recommended reading - 
https://scotch.io/tutorials/the-anatomy-of-a-json-web-token 
https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens

Though if you notice, the example is indeed using username+password rather then fb/ggl Oauth...
It would be awesome if anyone here can point out such an example...

**Comment by somus** [comment]
Authentication is something which will vary from project to project. Generally, it is not a good idea to have authentication in a boilerplate project. As Prashant suggested, we could have the mern-cli clone a different project which has implemented passport.js using mern for the people who want that. It can look something like this,

```
mern list
```

can output something like this

```
Available variants
--------------------------
passport-auth - MERN with passport.js
jwt-auth - MERN with JWT auth
redux-saga - MERN with redux-saga
```

You can clone a particular variant using

```
mern newApp passport-auth
```

I've created a separate discussion thread for this at hashnode/mern-cli#10. I'm closing this in favour of that. We can continue the discussion there.
