### ISSUE TITLE
Reducer selectedPost / post ?

### ISSUE THREAD

**Issue by andyfenelon** [Hashnode/mern-starter#119]
```
const initialState = { posts: [], selectedPost: null };

const postReducer = (state = initialState, action) => {
  switch (action.type) {
    case ActionTypes.ADD_POST :
      return {
        posts: [{
           ...
        }, ...state.posts],
        post: state.post };
```

in the initialState there is a variable called selectedPost but in the switch statement and throughout it seems to be referred to as post ?

**Comment by mayankchd** [comment]
It should be ```post``` in ```initialState``` too. Send a PR if you can.

**Comment by andyfenelon** [comment]
done https://github.com/Hashnode/mern-starter/pull/120
