### ISSUE TITLE
npm start cannot start the app on Windows

### ISSUE THREAD

**Issue by aneeshd16** [Hashnode/mern-starter#12]
The environment variable NODE_ENV cannot be set via the `npm start` command
```
PS B:\Projects\MERN\testApp> npm start

> mern-starter@1.0.0 start B:\Projects\MERN\testApp
> NODE_ENV=development node index.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

Using powershell on Windows 10. Does not work with cmd either.

Need to investigate a cross platform method for setting the environment variables and starting the server.

**Comment by prank7** [comment]
@aneeshd16  This [Commit ](https://github.com/Hashnode/mern-starter/commit/b031c038b153d4e05dbfd1c88542d2daaedcddba) should fix this issue.

**Comment by aneeshd16** [comment]
@prank7 Fixed!

**Comment by aneeshd16** [comment]
@prank7 Also need to add cross-env for the other scripts in package.json

**Comment by prank7** [comment]
@aneeshd16 Sure, maybe send a PR or I will fix it in sometime.
