### ISSUE TITLE
Use Radium ?

### ISSUE THREAD

**Issue by carloscuatin** [Hashnode/mern-starter#125]
that improve performance and add insulation of styles for each component

**Comment by SOSANA** [comment]
1+,

lets use this with postcss? https://github.com/postcss/postcss-js

**Comment by carloscuatin** [comment]
yes @SOSANA

**Comment by elaijuh** [comment]
I think css modules is better tho.

**Comment by Ajar-Ajar** [comment]
I agree with @elaijuh 
CSS Modules with post-css is the way to go!

**Comment by somus** [comment]
Closing in favour of #89. We can continue this discussion there.
