### ISSUE TITLE
Production bundle needs a hash name

### ISSUE THREAD

**Issue by elaijuh** [Hashnode/mern-starter#126]
For production use, i think the bundle needs a hash name. Currently the index is rendered with hardcoded `/dist/bundle.js`, if I use `[hash]` in webpack, then how can I pass it to `server.js` for rendering. Maybe I need [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin). Any idea or plan to implement this in MERN seed?

**Comment by joernroeder** [comment]
1+

**Comment by somus** [comment]
Done on c4b740d2956e77ea11f3bc9a539f8502b3890cab.
