### ISSUE TITLE
Support react-css-modules with classnames

### ISSUE THREAD

**Issue by elaijuh** [Hashnode/mern-starter#128]
That's quite common and convenient way of dealing with styles, I think it's good to be integrated in the seed. Should I PR for that?

**Comment by Ajar-Ajar** [comment]
+1

**Comment by joernroeder** [comment]
+1

**Comment by elaijuh** [comment]
PR is here  #138

**Comment by elaijuh** [comment]
ahh...unit test covers jsx comparison...that might take some time to fix

**Comment by somus** [comment]
Hey @elaijuh! We can continue having the discussion about css-modules at #89.
