### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by avioli** [Hashnode/mern-starter#13]
Mongo is so EXTREMELY vaguely mentioned, as if it is NOT a requirement.

I ran `npm start` twice, since after the first one I realised it might be a PORT issue, but it turned out it required Mongo.

Please, add this requirement more prominently.

I understand that

```
> npm install -g mern-cli
> mern <YourAppName>
```

sounds so hip and cool, but it is hardly enough.

**Comment by mrspeaker** [comment]
Yes - agree. I came looking for this issue: "why am I getting 'Error: connect ECONNREFUSED' when doing `npm start`? I followed the instructions exactly!"

**Comment by prank7** [comment]
We updated the README
