### ISSUE TITLE
newPost.slug Validation Error when newPost.tittle is Unicode such as CJK

### ISSUE THREAD

**Issue by Honghe** [Hashnode/mern-starter#131]
`newPost.slug == ""` after slugify when newPost.title is CJK or other Unicode, such as newPost.title="汉字"
This leads to Model Schema `Validation Error`

	// Let's sanitize inputs
	newPost.title = sanitizeHtml(newPost.title);
	newPost.name = sanitizeHtml(newPost.name);
	newPost.content = sanitizeHtml(newPost.content);

	newPost.slug = slug(newPost.title.toLowerCase(), { lowercase: true }); // newPost.slug == "" when newPost.title is CJK or other Unicode
	newPost.cuid = cuid();
	newPost.save((err, saved) => {
	if (err) {
	  return res.status(500).send(err);
	}
	return res.json({ post: saved });
	});

**Comment by somus** [comment]
`node-slug` which we are using doesn't support other language characters. We will look into using something else so that other language characters can be sluggifyed.
