### ISSUE TITLE
promiseUtils.js got some problems

### ISSUE THREAD

**Issue by elaijuh** [Hashnode/mern-starter#132]
I have tried nested routes with `need` function in both components for fetching data. Then it crashes

```javascript
export function sequence(items, consumer) {
  console.log(items)
  const results = [];
  const runner = () => {
    const item = items.shift();
    if (item) {
      return consumer(item)
        .then((result) => {
          results.push(result);
        })
        .then(runner);
    }

    return Promise.resolve(results);
  };

  return runner();
}
```

**Comment by mayankchd** [comment]
What error do you got?

**Comment by elaijuh** [comment]
@mayankchd it just hangs on the second promise. To reproduce the problem, you can add

```javascript
App.need = [() => {
   return Promise.resolve('null')
}]
```
to test multi-dependency

**Comment by mayankchd** [comment]
@elaijuh  Thanks! Will be fixing it!

**Comment by mayankchd** [comment]
@elaijuh  we are passingvwhatever is returned from every element of need to ```store.dispatch```,

in your case ```() => {
   return Promise.resolve('null')
}``` doesn't returns a valid action type or a thunk

Do
```
App.need = [() => {
  return (dispatch) => {
    return Promise.resolve('null');
  };
}];
```

Also nested routes with need function are working fine for me.
