### ISSUE TITLE
add combineReducers to a RootReducer

### ISSUE THREAD

**Issue by Ajar-Ajar** [Hashnode/mern-starter#134]
At the moment the postReducer is the only reducer and is considered as a root reducer.
In most apps there is more then one reducer so a proper root reducer will use combineReducers to combine all existing reducer into a common interface used by the store.

**Comment by joernroeder** [comment]
had exactly the same problem when i added redux-form to my app. solved it by creating the following `shared/redux/reducers/rootReducer.js`:

```javascript
import { combineReducers } from 'redux';
import { reducer as formReducer } from 'redux-form';

import appReducer from './reducer';

const reducers = {
	app: appReducer,
	form: formReducer,
};

const reducer = combineReducers(reducers);

export default reducer;
```

after replacing `reducers/reducer` with `reducers/rootReducer` in the `redux/store` directory everything worked fine. 

hope that helps.

**Comment by Ajar-Ajar** [comment]
It certainly does, I think this needs to be a part of the Mern-starter.
I wonder what other reducer can we include in the initial boilerplate and send a PR that implements it...

**Comment by somus** [comment]
Fixed in v2 branch.
