### ISSUE TITLE
Server side initial render is different than client side

### ISSUE THREAD

**Issue by kevinliang** [Hashnode/mern-starter#139]
When running npm start for the first time, the console gives me a warning.  Any way to fix this?

warning.js?0260:44Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:

(client) ta-reactid="2"><div data-reactid="3"><di
 (server) ta-reactid="2"><div class="header" data-

**Comment by joernroeder** [comment]
maybe it's just because there is an additional wrapper `<div>` with devTools enabled?
https://github.com/Hashnode/mern-starter/blob/master/client/index.dev.js#L16

**Comment by kevinliang** [comment]
hmm you're right. thx!

**Comment by jforaker** [comment]
@kevinliang @joernroeder how did you fix the issue?  It still happens on a fresh install 5/14/2016

**Comment by joernroeder** [comment]
@jforaker I didn't do anything :) I think it's ok to rerender the initial view on the client during development to add the redux dev tools. The server side rendering will be fine when you switch to production mode.

You can start the server in production mode via `npm start:prod`

**Comment by jforaker** [comment]
You are right, thanks!

**Comment by joernroeder** [comment]
@jforaker you're welcome :)

**Comment by jforaker** [comment]
Actually @joernroeder I think that could be a false positive..  The react warning does not run in production mode.

From warning.js line 24: 
`process.env.NODE_ENV !== 'production' ...`

**Comment by joernroeder** [comment]
@jforaker yes, warnings are disabled during production but everything is correct. :)
During development the server side uses the else block at https://github.com/Hashnode/mern-starter/blob/master/client/index.dev.js#L24 (the CLIENT environment variable is set in the webpack config) while the client passes the if statement and renders the additional `<div>` and the DevTools.

During production client and server code is exactly the same.
https://github.com/Hashnode/mern-starter/blob/master/client/index.prod.js#L13

**Comment by joernroeder** [comment]
@jforaker I've installed the the [redux devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) and opened them in a chrome panel and the warning disappeard.

**Comment by abotchen** [comment]
server side and client side should use match
