### ISSUE TITLE
Add href to Links post items on main page.

### ISSUE THREAD

**Issue by prank7** [Hashnode/mern-starter#15]
Add href to post items in [PostListItems](https://github.com/Hashnode/mern-starter/blob/master/shared/components/PostListItem/PostListItem.js), so that it renders correctly, even if JS is disabled in browser.

**Comment by noahlocke** [comment]
@prank7 not sure I understand, seems to render fine w/js turned off, but then again I just don't think I'm understanding what you're asking for...

**Comment by prank7** [comment]
@noahlocke Its fixed. This should have been closed.
