### ISSUE TITLE
mern-mui

### ISSUE THREAD

**Issue by hounded** [Hashnode/mern-starter#150]
Hi
I noticed talk about the mern cli cloning different repositories, with that in mind I took the mern-starter and kept as much as possible and implemented [mern-mui starter blog](https://github.com/hounded/mern-starter/tree/mui) can submit a pull request if you just want to see how much has changed. 

Anyway it would need review but it is there for you if you want to start a hashnode mern-mui-starter

**Comment by SOSANA** [comment]
Why did you close this? I think this is a great idea

**Comment by somus** [comment]
@hounded Awesome! You are fast. We are yet to modify mern-cli to allow cloning of variants. We are looking to completing it within this week. I surely will get back to you after that. Meanwhile, keep an eye on the v2 branch. We are changing a lot of things there.

**Comment by hounded** [comment]
Yeah hi guys closed it as it is based of v1 and looking at v2 the file structure has changed, started working on a passport authentication for v2. Material Ui is giving me unmet dependencies on webpack in mern v2

**Comment by hounded** [comment]
ok so I built a [mern-mui](https://github.com/hounded/mern-starter/tree/mui) branch for v2 using what you have come up with so far.

**Comment by SOSANA** [comment]
@hounded look forward to checkin this out :+1:

**Comment by somus** [comment]
@hounded MERN v2 is released. Check out the [docs](http://mern.io/documentation.html#make-your-mern) to find out how to submit your version of MERN to mern-cli.

**Comment by MobileAppVault** [comment]
Is there any progress on that?

**Comment by hounded** [comment]
I gave up, and fell back to symfony as the mern framework is imo not quite all there for a average/morderate programmer to provide a robust production application. 

Show me a package that can plug in to MERN and provide the same user functionality as symfony's
FOSUserBundle and I will swap back to MERN, 
but for now there is only some half ass projects that implement passport in an isomorphic application.
Password resetting?
Remember me cookies?
Security around routes?
