### ISSUE TITLE
Configure mern with nginx?

### ISSUE THREAD

**Issue by JimmyMow** [Hashnode/mern-starter#151]
Apologize if this is a stupid question but does anyone know how I would configure mern with nginx given that there is no static html file?

**Comment by somus** [comment]
You need to Nginx reverse proxy. The config will look something like this
```
server {
    listen 80;

    server_name example.com;

    location / {
        proxy_pass http://APP_IP_ADDRESS:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```
`APP_IP_ADDRESS` will be `127.0.0.1` if you are running the application in the same server.

**Comment by andyfaizan** [comment]
How does one serve the dist folder generated by mern using nginx? Unfortunately I'm not experienced with nginx and hence could not get it to work. The absence of an index.html also makes things a bit tricky.

**Comment by mattlubner** [comment]
It's not possible to host `dist/` with _only_ Nginx, as Mern dynamically generates the site index in its Node process. @somus's answer is showing how to put Nginx in front of that Node process, using an Nginx reverse proxy to forward requests to Node.

**Comment by andyfaizan** [comment]
Thanks @mattlubner for the explanation.
