### ISSUE TITLE
once I run npm start I got an error

### ISSUE THREAD

**Issue by NouranMahmoud** [Hashnode/mern-starter#152]
![errormern](https://cloud.githubusercontent.com/assets/5081150/15801612/22d94f34-2a9b-11e6-939b-4d9660f087b4.png)

I've got this error once I run `npm start`.. any idea?

**Comment by hounded** [comment]
Do you have mongo started?
Also can try webpack dev changing 0.0.0.0 to localhost

**Comment by NouranMahmoud** [comment]
Oh my bad, I was running another server on the same port and I didn't start mongodb. Thanks for your prompt reply.
