### ISSUE TITLE
babel-plugin-webpack-loaders approach

### ISSUE THREAD

**Issue by Stalso** [Hashnode/mern-starter#165]
Hello. In v2 brunch you are using `babel-plugin-webpack-loaders` . This plugin is cool and it solves all problems with server-side rendering ( like `import 'sanitize.css/sanitize.css';` ). But is it unversal approach? For example, I want to try to rewrite your project using TypeScript. This Babel plugin will not help me in this way. Maybe you should use something like [this](https://github.com/halt-hammerzeit/universal-webpack)  library? It is from `webpack-isomorphic-tools` author.

**Comment by somus** [comment]
Thanks for the sharing the library. It looks good.

Maybe a PR implementing that?

**Comment by Stalso** [comment]
Unfortunately,  I am not able to implement that, I am rather new in all this stuff.  My main goal is to implement ssr in  [this](https://github.com/mxstbr/react-boilerplate)  template,  and I can not manage with the task.  Another my goal is to make Mern server side debuggable in some IDE. .And I am also do not have an idea,  how to do this.  If I can not implement such tasks,  I do not think,  that I am capable with such task.

**Comment by mannyhenri** [comment]
Many changes coming with using webpack V4. closing for now.
