### ISSUE TITLE
[Question] Any suggestions to help debug the server side code via gui tools ?

### ISSUE THREAD

**Issue by aga5tya** [Hashnode/mern-starter#169]
I am trying to debug the server side api's using some tools like node-inspector, iron-node and devtool with no success. Has anyone implemented debugging feature into this stack? What i am looking for is to be able to debug the code with the source maps enabled on server side, possibly initiating via npm script when node environment is set to development mode. Any suggestions or pointers to any fork implementing this would really help me. 

P.S
I am building my app on 2.0 branch of mern.

**Comment by Stalso** [comment]
Also do not have an idea,  how to deal with it

**Comment by aga5tya** [comment]
This is what worked for me, not sure if it's the best approach, open to suggestions.

I added the following script in package.json with node-inspector@0.12.8(global) and concurrently@2.1.0(local) installed. When i launch http://127.0.0.1:8080/?port=5858, debugger gui loads with source maps and breakpoints on api's are working too.

"debug": "concurrently \"node-inspector --save-live-edit\" \"cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon --debug index.js\""

**Comment by Stalso** [comment]
I can not even imagine, why and where sourcemap for server side are generated. It is magic. Have you  tried to do the same in some IDE? I have tried to build server with source maps and run transpiled code in web strom, but it does not work

**Comment by aga5tya** [comment]
Even i wonder how server side code has sourcemaps by default, i suppose it's because of babel-register or babel-polyfill being required in the server entry point. @somus: could you please clarify this?

And i use atom editor with terminal inside it and don't use IDE's, so not sure about running the app in them.

**Comment by Stalso** [comment]
@aga5tya But I am. Net developer.  I am used to cool and powerful IDE.  I do not want to hold one browser tab for results and debugging client side,  one tab for server debugging and editor window for coding. I am trying to discover something new for and all this javascript stuff is really funny ( especially React) but developer experience (especially on server) is bad.  Or maybe I do not know something.  I can not even imagine how Node.js developers implement some complicated backend logic.  For example Mern.  It is cool for client side,  but I have no idea,  how II should make server development. As for me I,  have implemented separated `api server` and proxy my calls to it.  For debugging api server I am transpilling it with source map and run generated files with separate instance of debugger.

**Comment by SOSANA** [comment]
I solved some issues today using this...

Debugging NodeJs and Webpack Loaders
https://forum.shakacode.com/t/debugging-nodejs-and-webpack-loaders/142
```npm install -g node-inspector```
change script in package file to this or add new script 'start2'
```"start": "cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development node-debug index.js"```
than go to your server.js file and add where applicable
```debugger```
than go cli and ```npm start``` or ```npm start2```
a gui debugger will show up :+1:

**Comment by SOSANA** [comment]
I solved some issues today using this...

Debugging NodeJs and Webpack Loaders
https://forum.shakacode.com/t/debugging-nodejs-and-webpack-loaders/142
```npm install -g node-inspector```

change script in package file to this or add new script 'start2'
```"start": "cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development node-debug index.js"```
than go cli and ```npm start``` or  ```npm start2```

a gui debugger will show up

**Comment by SOSANA** [comment]
@aga5tya you mentioned "debug the server side api's" have you tried postman from chrome dev tools found [here](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en)? or tried http://swagger.io/ ? [here](http://editor.swagger.io/#/) is the demo
![temp](https://cloud.githubusercontent.com/assets/2634185/16353569/8e3d0088-3a39-11e6-8a8b-29d91e484474.PNG)


regarding node-inspector 
```npm install -g node-inspector```
in your script file do the following, notice the replacement of ```nodemon```?
```"start": "cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development node-debug index.js",```
than go to your server.js file and add ```debugger``` where you want the breakpoints to be place than start stepping through etc

**Comment by aga5tya** [comment]
@SOSANA : Looking into what swagger.io has to offer. But running node-debug instead of nodemon would kill my server changes being watched right ? nodemon is restarting the server for me automatically watching the file changes.

**Comment by Stalso** [comment]
Finally, I have found solution. It is not very cool, bur it works. I have made webpack bundle for server (with source maps). Then, to debug server code in WebStorm, you need to start debugging for this bundle (not for the original code), and it will stop on breakpoints of original code. If you use Visual Studio Code, you should add in `webpack.config` for server this lines:

    output: {
      pathinfo: true,
      filename: 'server.js',
      
      // If need vscode debugging support uncomment this lines
      // devtoolModuleFilenameTemplate        : '[absolute-resource-path]',
      // devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]'
    }

And then start original server code. Also for VsCode you should make correct `launch.json`

        {
            "version": "0.2.0",
            "configurations": [
                {
                    "name": "Launch",
                    "type": "node",
                    "request": "launch",
                    "program": "${workspaceRoot}/server/index.js",
                    "stopOnEntry": false,
                    "args": [],
                    "cwd": "${workspaceRoot}",
                    "preLaunchTask": null,
                    "runtimeExecutable": null,
                    "runtimeArgs": [
                        "--nolazy"
                    ],
                    "env": {
                        "NODE_ENV": "development"
                    },
                    "externalConsole": false,
                    "sourceMaps": true,
                    "outDir":  "${workspaceRoot}/build"
                },
                {
                    "name": "Attach",
                    "type": "node",
                    "request": "attach",
                    "port": 5858,
                    "address": "localhost",
                    "restart": false,
                    "sourceMaps": false,
                    "outDir": null,
                    "localRoot": "${workspaceRoot}",
                    "remoteRoot": null
                }
            ]
        }

**Comment by ryanmeisters** [comment]
Per [this thread ](https://github.com/node-inspector/node-inspector/issues/905) it sounds like node-debug is broken in > 6.3.1. 

As suggested in that thread though, `node --inspect --debug-brk` is working for me on a fresh clone of mern with node v6.6.0. 

Added a debug script to my package.json
```
"debug": "cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development node --inspect --debug-brk index.js",
```
