### ISSUE TITLE
"Cannot find module './dist/manifest.json'" while "npm run start:prod"

### ISSUE THREAD

**Issue by osenvosem** [Hashnode/mern-starter#171]
```
myapp (master) » npm run start:prod                                                                   ~/dev/two/myapp

> mern-starter@2.0.0 start:prod /Volumes/Data/development/dev/two/myapp
> cross-env NODE_ENV=production node index.js

module.js:442
    throw err;
    ^

Error: Cannot find module './dist/manifest.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Data/development/dev/two/myapp/index.js:6:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```
There is no dist folder created.

**Comment by stephan281094** [comment]
If I'm not mistaken you can run `npm run bs`, this will clean everything, build the dist files and then start your server in production.

**Comment by osenvosem** [comment]
@stephan281094 yes, it works, but it isn't mentioned in documentation:

Available Commands

npm run start - starts the development server with hot reloading enabled
npm run start:prod - bundles the code and starts the production server
npm run test - start the test runner
npm run watch:test - start the test runner with watch mode
npm run coverage - generates test coverage report
npm run lint - runs linter to check for lint errors

**Comment by stephan281094** [comment]
Good point. Perhaps it should be added :)

**Comment by osenvosem** [comment]
@stephan281094 thank you, by the way. =)

**Comment by stephan281094** [comment]
@osenvosem No problem!

**Comment by somus** [comment]
My bad. Updated the readme with correct command.
