### ISSUE TITLE
npm install takes 5 minutes to run

### ISSUE THREAD

**Issue by ranyefet** [Hashnode/mern-starter#177]
Hello, 

This looks like a cool project, really like the features (except for Mongo dependency)
I've just created a new app to play with it, but wow, so much dependencies.
It took more then 5 minutes to install and the end result is:
**4151 directories, 26969 files = 541MB** 

Its crazy that we need 27K files before even writing a single line of code. 

I did noticed that the final build is around 120KB min & gzip which is great but the whole package feels too heavy in my opinion.

Is there any plans in the roadmap to make this starter slimmer and lightweight? maybe create a core start package with only what necessary and have a  plugin based system to add missing pieces?

Thanks,
Ran.

**Comment by SOSANA** [comment]
@ranyefet you can't have your cake and eat it too. 

You need a bare bones production app this is bare bones. Its called MERN for a reason. If anything I would like to add more features hince why they are introducing modules and mern-cli to build those modules.

What would you remove? 

If you feel you could live without some features, do a pr and it can be an option for others looking for a smaller foot print. Maybe no server, just dev server provided by webpack with no database, no server models, or controllers. no international language feature, code splitting, universal render, css modules/postcss,, etc.

Last few days I can see your point. I make small change on server or front end it takes like several mins for it to rebuild our bundles. Image when we add more modules for user/auth, other features etc. 

There is tons of boilerplate react and redux out there but very few quality production boilerplate entry apps with universal/isomorphic rendering wired up for you.

Do a PR or just google basic boilerplate for react and redux.I'd like to hear you or others recommendations on how we could reduce the foot print of this boilerplate app without taking away current features as it is.

**Comment by somus** [comment]
@ranyefet Thanks for the suggestion.

There is room for improvement in that. Plugin based system sounds interesting. From the top of my head, I think we can remove the server setup and make it into a separate addon.

What do you think are the things which can be removed from the current setup to make it light?

**Comment by maxenceC** [comment]
Totally agree with @ranyefet, MERN looks interesting, out-of-the-box docker config is pretty awesome.

But I just cloned the project, and without writing a single line of code/adding assets, after installing dependencies, the whole dev. project is 1,47 Go. It's huge.

Would it be possible with mern-cli to strip some parts ?

**Comment by mannyhenri** [comment]
with all the improvements we're looking at this might be resolved, closing for now.
