### ISSUE TITLE
Error installing webpack@2.1.0-beta.13

### ISSUE THREAD

**Issue by leocristofani** [Hashnode/mern-starter#178]
```
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.13 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer extract-text-webpack-plugin@1.0.1 wants webpack@^1.9.11
npm ERR! peerinvalid Peer chunk-manifest-webpack-plugin@0.1.0 wants webpack@^1.4.0-beta6
npm ERR! peerinvalid Peer webpack-dev-middleware@1.6.1 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer babel-plugin-webpack-loaders@0.7.0 wants webpack@>=1.12.9 <3.0.0
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.0 wants webpack@^2.1.0-beta
```

**Comment by SOSANA** [comment]
I haven't checked other packages but for example I know babel-plugin-webpack-loaders is dependent on beta 7 but works fine with beta 8, did your app start after npm install?

**Comment by leocristofani** [comment]
It's taking forever to start. Seriously, since you added your comment I ran `npm start` and left it there while working on other stuff. I assume it's an error.

Also, forgot to mention that this error only happened after I delete the node_modules, installed node v4.4.5 and npm v2.15.5 and ran `npm install` again. An just out of curiosity, I deleted node_modules because `npm test` or `npm test:watch` were throwing errors, too. By this is another issue I'll try again and open if needed.

**Comment by SOSANA** [comment]
ya took just over 5mins to start app, yikes

**Comment by hegelstad** [comment]
+1

**Comment by somus** [comment]
Upgrading to npm 3, delete `node_modules` and re-run `npm install`. That should fix the problem.
