### ISSUE TITLE
Mern throws error, crashes, immediately after starting server

### ISSUE THREAD

**Issue by nickfedoroff** [Hashnode/mern-starter#18]
`mern start`, then:

```
> mern-starter@1.0.0 start /Users/me/MernTest
> cross-env NODE_ENV=development node index.js

MERN is running on port: 8000! Build something amazing!

/Users/me/MernTest/node_modules/mongodb/lib/server.js:236
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! nom  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! mern-starter@1.0.0 start: `cross-env NODE_ENV=development node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mern-starter@1.0.0 start script 'cross-env NODE_ENV=development node index.js'.

```

**Comment by prank7** [comment]
Seems like your MongoDB is not running or its running on a different port.

**Comment by iisutton** [comment]
@nickfedoroff https://docs.mongodb.org/getting-started/shell/installation/

**Comment by ericnkatz** [comment]
```Caveats
To have launchd start mongodb at login:
  ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
Then to load mongodb now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
Or, if you don't want/need launchctl, you can just run:
  mongod --config /usr/local/etc/mongod.conf```

**Comment by ericnkatz** [comment]
@nickfedoroff See caveats if you use homebrew to install:
```
To have launchd start mongodb at login:
  ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
Then to load mongodb now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
Or, if you don't want/need launchctl, you can just run:
  mongod --config /usr/local/etc/mongod.conf```

**Comment by erichardson30** [comment]
@nickfedoroff I ran into pretty much the same issue as you initially. Make sure you have Mongodb installed on your computer and that it's running https://docs.mongodb.org/getting-started/shell/tutorial/install-mongodb-on-windows/
That fixed the issue for me

**Comment by ghoshnirmalya** [comment]
First, you will have to install and run mongoDB. Follow the following steps:

1. **brew update**
2. **brew install mongodb**
3. **brew install mongodb --with-openssl**
4. **brew install mongodb --devel**
5. **sudo mkdir -p /data/db**
6. **sudo chown -R <username> /data/db**
(Replace <username> with your username which you can get by typing **whoami** in the terminal)
7. **mongod**

Got to localhost:8000.

**Comment by jose920405** [comment]
complementing `ghoshnirmalya's` answer 

point 6:

`sudo chown youruser /data/db`

**Comment by Sammy0807** [comment]
After the mern blog appears the first time,  once I refresh the page, I get a typeError: cannot read property 'map' of undefined 
On client/modules/post/components/postlist.js 10:9
