### ISSUE TITLE
npm run start fails on windows with latest code.

### ISSUE THREAD

**Issue by kishanj918** [Hashnode/mern-starter#180]
I am using windows 10.  I have created new app using latest updates. When i ran npm start, it's giving me error `vendor.js:623GET http://0.0.0.0:8000/1.app.js net::ERR_ADDRESS_INVALID`
`vendor.js:656 Error: Loading chunk 1 failed.(…)__webpack_require__.oe @ vendor.js:656(anonymous function) @ routes.js?5936:29`
`vendor.js:619 Uncaught (in promise) Error: Loading chunk 1 failed.(…)`

**Comment by SOSANA** [comment]
@kishanj918 I just did a refresh install and npm start less than 30mins ago, everything working...you still having problems? you made sure to start mongod right?

I just opened a PR to fix a few bugs for HMR errors showing up in console.
