### ISSUE TITLE
run code on another machine

### ISSUE THREAD

**Issue by leranf** [Hashnode/mern-starter#183]
A friend of mine tried cloning my repo to view the app on his local machine, but npm install does not complete. I want this to be an open source project that anyone can download and reuse...is there something I need to configure to allow that?

Thanks, loved using the boilerplate!!

**Comment by somus** [comment]
what error did he get?

**Comment by leranf** [comment]
Failed to parse package.json data
Package.json must be actual json, not just JavaScript 

Leran
