### ISSUE TITLE
Support for GraphQL and Relay

### ISSUE THREAD

**Issue by fuentesjr** [Hashnode/mern-starter#184]
I'm curious what are people's thoughts on adding these two layers to the stack? Have they been considered before? Would this be better supported via a MERN variant instead?

**Comment by somus** [comment]
A MERN variant would be great.

You might want to check out [apollo stack](http://www.apollostack.com/) if you have not already done. It might be a good starting point.

**Comment by somus** [comment]
Closing this for now. If you have made a mern variant with GraphQL and Relay, I will gladly add it to mern-cli.
