### ISSUE TITLE
Where to register client components to propagate changes

### ISSUE THREAD

**Issue by zatziky** [Hashnode/mern-starter#189]
Yesterday I installed the mern-starter project. I was playing around a bit modifying `PostListItem` and others. All the changes were propagated to the client quite fast.

Then I decided to add my own component. In file system structure I put it next `client\modules\Post` thus `client\modules\MyModule` with a sole file `components\SearchDomainInput.js`. 

The problem is any changes on `SearchDomainInput` are propagated only on server startup even though in the terminal I can see 

> webpack building...
> webpack  e9c15d7d435381a63771 in 1043ms

I put then my component under `client\modules\Post` and things started to work again. I was not able to find where to register my components so that webpack can pick them up.

Thank for your help!

**Comment by osenvosem** [comment]
If I get it right you need add your module to [this section](https://github.com/Hashnode/mern-starter/blob/master/client/routes.js#L17-L21) in order to use HMR with async components loading.

**Comment by zatziky** [comment]
I had to reference it in `import` then it started to work. And yes, I had to add it to "that" section too.
