### ISSUE TITLE
how to use <img />?

### ISSUE THREAD

**Issue by colinshen** [Hashnode/mern-starter#194]
i tried using it like this
```
<img src="./xxx.png">
```
but it could not load image 
also, when i build my project（production）. I got this error
```
ERROR in ./~/css-loader?localIdentName=[hash:base64]&modules&importLoaders=1!./~/postcss-loader!./client/modules/About/components/AboutJumbotron/AboutJumbotron.css
    Module not found: Error: Can't resolve 'about.png' 
```

**Comment by Amigos466** [comment]
I have same problem, but when i run "npm run bs" images loaded well.

**Comment by colinshen** [comment]
@Amigos466  the second problem I mentioned was that those images I used in my css file. not <img/>. do you have the first problem?

**Comment by Amigos466** [comment]
Yes, i have, but i dont know what i can do. Also i have problem with msbuilder, look in the issues list,  its first. Mayby its because of this? Do you have something like this?

**Comment by colinshen** [comment]
I dont have that...

**Comment by Amigos466** [comment]
On Ubuntu 14.04 all okay . But in my browser on Windows 7 does not show the pictures . This is because the way the form http://0.0.0.0/imagepath.png. I tried to replace the relative path and it worked . I think you need to reconfigure webpack.

**Comment by Amigos466** [comment]
let images = './pathtoimages/'; -after imports

<img src={require(images+"yourimage.png")} />

**Comment by ozkey** [comment]
In regards to PNG not rendering on header I fixed it by changing the line below in "webpack.config.dev.js"
publicPath: 'http://127.0.0.1:8000/',

I hope this helps

**Comment by somus** [comment]
You have require or import the image, not just give the path. Then only, webpack will import the required file. Examples for importing in [react component](https://github.com/Hashnode/mern-starter/blob/master/client/modules/App/components/Footer/Footer.js#L8-L12) and [css file](https://github.com/Hashnode/mern-starter/blob/master/client/modules/App/components/Header/Header.css#L2).

Let me know if it helps.

**Comment by colinshen** [comment]
@somus it worked. how can i change the favicon?

**Comment by somus** [comment]
Replace the favicon url [here](https://github.com/Hashnode/mern-starter/blob/master/server/server.js#L77).
