### ISSUE TITLE
Some problems with "...\msbuild.exe` failed with exit code: 1"

### ISSUE THREAD

**Issue by Amigos466** [Hashnode/mern-starter#195]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\Nagibator\WebstormProjects\DotaItems\node_modules\nodejieba\build\nodejieba.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Nagibator\WebstormProjects\DotaItems\node_modules\nodejieba
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
I want to know what does it mean and how fix it? Anyway mern-starter continue install and finish with 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN babel-plugin-webpack-loaders@0.7.0 requires a peer of webpack@>=1.12.9 <3.0.0 but none was installed.
npm WARN chunk-manifest-webpack-plugin@0.1.0 requires a peer of webpack@^1.4.0-beta6 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.

**Comment by Amigos466** [comment]
I did it already . But it did not help. My local version node-gyp 3.4.0. As far as I know , first boot the local unit , which is specified in the dependencies . Thanks for the reply and sorry for my bad english .

**Comment by Amigos466** [comment]
Resolve problem, who have same problem just delete in C:\Program Files\nodejs\node_modules\npm\ node-gyp folder and config  AND reinstal node-gyp as say @rodeyseijkens

**Comment by pabhale2** [comment]
@rodeyseijkens,

This error is fixed in node-gyp v3.4.0, you are still using node-gyp v3.3.1

npm uninstall -g node-gyp
npm install -g node-gyp

This will install the lastest version

It works for me. Thanks

**Comment by tharun06** [comment]
C:\..\..\.>npm install oracledb

> oracledb@1.13.1 install C:\project\dqf\src\node_modules\oracledb
> node-gyp rebuild


C:\..\..\.node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Users\..\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0002: Failed to execute command: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe" @C:\Users\..\AppData\Local\Temp\tmp1088ea37de474c999e0089bebae5f5c4.rsp". The o


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\..\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\..\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\project\dqf\src\node_modules\oracledb
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN DQF@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\muthotk\AppData\Roaming\npm-cache\_logs\2017-08-18T15_05_05_483Z-debug.log

//Can anyone help me out

**Comment by Trinyoung** [comment]
there is no node-gyp folder or config in  C:\Program Files\nodejs\node_modules\npm\ .I find the node-gyp folder in the  C:\Program Files\nodejs\node_modules\npm\ . where is the config?

**Comment by Trinyoung** [comment]
there is no node-gyp folder and config in  C:\Program Files\nodejs\node_modules\npm，the node -gyp folder is in C:\Program Files\nodejs\node_modules\npm\node_modules;the last question ,where is the config,the config has another name? configure  in C:\Program Files\nodejs\node_modules\npm or config-chain in C:\Program Files\nodejs\node_modules\npm\node_modules

**Comment by Trinyoung** [comment]
I have the same question but your method doesn't work

**Comment by isaadansari** [comment]
You need to download MS build tools for this to be working.

**Comment by courageDeveloper** [comment]
Would love to get the answer to this

**Comment by navmed** [comment]
1. Zap node-modules. I use:

````
rd /s /q node_modules
````

2. Delete package-lock.json

3. Uninstall and reInstall node-gyp globally as pabhale2 suggested
````
npm uninstall -g node-gyp
npm install -g node-gyp
````
4. Run npm install now, it should work.

**Comment by ronaldvenegas1991** [comment]
> 1. Zap node-modules. I use:
> 
> ```
> rd /s /q node_modules
> ```
> 
> 1. Delete package-lock.json
> 2. Uninstall and reInstall node-gyp globally as pabhale2 suggested
> 
> ```
> npm uninstall -g node-gyp
> npm install -g node-gyp
> ```
> 
> 1. Run npm install now, it should work.





@navmed This works for me. Thanks!
