### ISSUE TITLE
importing .scss files

### ISSUE THREAD

**Issue by mmintel** [Hashnode/mern-starter#197]
Hi there,

i have installed sass-loader and node-sass to my project and added this line into my webpack.config.babel.js and webpack.config.dev.js 

```
      {
        test: /\.scss$/,
        loader: 'style-loader!css-loader?localIdentName=[name]__[local]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader!sass-loader'
      },
```

but I am always getting this error when importing .scss file:

```
/Users/mmintel/Projekte/writr/node_modules/react-toolbox/lib/app_bar/theme.scss:1
(function (exports, require, module, __filename, __dirname) { @import "../colors";
                                                              ^

SyntaxError: Unexpected token ILLEGAL
```

What's wrong with it?

**Comment by phaneendra** [comment]
Would need to have .scss in resolve extensions.

 resolve: {
    extensions: ['', '.js', '**scss**', '.jsx'],
    modules: [
      'client',
      'node_modules',
    ],
  },

**Comment by p-le** [comment]
`  resolve: {
    extensions: ['', '.scss', '.js', '.jsx'],
    modules: [
      'client',
      'common',
      'node_modules',
    ],
  },
  module: {
    loaders: [
      {
        test: /\.(scss|css)$/,
        exclude: /node_modules/,
        loader: 'style-loader!css-loader?localIdentName=[name]__[local]__[hash:base64:5]&modules&importLoaders=1&sourceMap!postcss-loader!sass-loader'
      },
      {
        test: /\.jpe?g$|\.gif$|\.png$|\.svg$/i,
        loader: 'url-loader?limit=10000'
      }
    ],
  },`

My current webpack.config.babel.js but it still gives me same error when loading react-toolbox them.css

**Comment by fabianm** [comment]
I ran into the same problem today. I found out the following configuration worked.

**webpack.config.babel.js**:
```js
{
    test: /\.scss$/,
    loaders: 'css-loader/locals?localIdentName=[name]__[local]__[hash:base64:5]&modules&importLoaders=1!sass-loader',
},
```

**webpack.config.dev.js**:
```js
{
    test: /\.scss$/,
    loader: 'style-loader!css-loader?localIdentName=[name]__[local]__[hash:base64:5]&modules&importLoaders=1&sourceMap!sass-loader?sourceMap',
},
```

**webpack.config.prod.js**:
```js
{
    test: /\.scss$/,
    exclude: /node_modules/,
    loader: ExtractTextPlugin.extract({
        fallbackLoader: 'style-loader',
        loader: 'css-loader?localIdentName=[hash:base64]&modules&importLoaders=1!sass-loader',
     }),
},
```

Does that work for you? The magic here is `css-loader/locals` in `webpack.config.babel.js` which only exports identifier mappings.

**Comment by Bonitis** [comment]
@fabianm this did not work for me. I am trying to use a single `main.scss` file that I had previously built in mern v1. Is there any other configuration changes besides that ones you mentioned? 

This is working for me in dev, and I'm pretty sure it is not the correct way to go about this:

**webpack.config.babel.js**
`{
    test: /\.scss$/,
    loaders: ['style', 'css', 'sass'],
},`

**webpack.config.dev.js**
`{
     test: /\.scss$/,
     loaders: ['style', 'css', 'sass'],
},`

I tried the same in prod and it runs but it does not compile any styles.

**Comment by fabianm** [comment]
@Bonitis What is your Webpack production configuration?

**Comment by Bonitis** [comment]
@fabianm It is standard for mern v2, and I tried out your suggestion. If I use the same line in prod that I have for dev and babel I get an error that scss is not a supported file type.

**webpack.config.prod.js**
` {
      test: /\.scss$/,
      exclude: /node_modules/,
      loader: ExtractTextPlugin.extract({
         fallbackLoader: 'style-loader',
         loader: 'css-loader?localIdentName=[hash:base64]&modules&importLoaders=1!sass-loader',
  })`

I do also have `extensions: ['', '.js', '.jsx', 'scss'],` in all three config files.

**Comment by fabianm** [comment]
@Bonitis To be clear, you are able to build the server and client, but no stylesheet files are created? Does the element you are using the style on have a corresponding class name?

Could it be that you are only importing the stylesheet, but not actually using it? Like this:

```js
import style from './main.scss';

export default function Component() {
    return (
        <div className={style.header}>Header</div>
    );                   ^
}                        You are not doing this
```

**Comment by Bonitis** [comment]
@fabianm yes I am able to build the server and client but no style sheets are created. I realize now that I am not using my stylesheet the way post-css wants me to. I removed references to the style modules and only have this:

**client/App.js**

`// Base stylesheet
require('./main.scss');`

For now, I'd like to keep using my one scss file for the whole app because I'm porting over from mern v1. What is the best way to accomplish that, or should I work towards converting to post-css?

The other option I am going to try is going back to my setup from mern v1. These were the scripts I had before:

**package.json**

`"minify-sass": "npm run build-css && cleancss -o static/css/public.min.css static/css/public.css",
"build-css": "node-sass --include-path scss static/sass/main.scss static/css/public.css",`

**Comment by Bonitis** [comment]
My stylesheet is now running in both dev and prod. I had used [this PR](https://github.com/Hashnode/mern-starter/pull/50) before and it worked wonderfully, so I basically repeated that here. This is my current setup:

**package.json** (install clean-css)
`"start": "npm run build-css && cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js",`
`"minify-sass": "npm run build-css && cleancss -o dist/app.min.css dist/app.css",`
`"build-css": "node-sass --include-path scss client/main.scss dist/app.css",`
`"build": "cross-env NODE_ENV=production webpack --config webpack.config.prod.js && npm run minify-sass",`

**webpack.config.prod.js**
`{
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['style', 'css', 'sass'],
      },`

**server.js**
`const sassPath = process.env.NODE_ENV === 'production' ? '/app.min.css' : '/app.css';`
`<link rel="stylesheet" href=${sassPath} />`

**Comment by fabianm** [comment]
@Bonitis If you add explicit references to stylesheet, like in the example in my previous comment, is the stylesheet still not getting created?

By the way, have you correctly configured the ExtractTextPlugin?

**Comment by devourment77** [comment]
@mmintel or @p-le did either of you resolve your sass issues?  Hitting the same error.
