### ISSUE TITLE
No global installation of mern-cli and cross-env please

### ISSUE THREAD

**Issue by fibric** [Hashnode/mern-starter#20]
Hi,

Can we put mern-cli into `scripts` section of `package.json`, please.
Each project can have it's own mern-cli version.

```javascript
...
"scripts": {
  ...
  "mern-cli": "mern-cli",
  "cross-env": "cross-env",
  ...
}
...
```

Now we can use mern-cli by calling npm. `npm run mern-cli <mern-cli-command>` or `npm run cross-env <cross-env-command>`

**Comment by sandeeppanda92** [comment]
Hi Denny

Right now `mern-cli` doesn't do much apart from cloning `mern-starter` project. But we have some great plans for future (Roadmap being prepared). By passing some flags to `mern` command, one should be able to configure the project in a different way. For instance, you can run `mern app --withLifeCycle` which will create React components with life cycle functions. 

Let us know what you think.

**Comment by christiansakai** [comment]
+1, like that idea

**Comment by fibric** [comment]
We can do all this and don't need to install `mern-cli` globally.

I had many troubles with `gulp` while I had it globally installed and in some not so frequently updated projects, gulp failed to run tasks after some time.

When we put `mern-cli` to `scripts` of `package.json` we can still run all Mern commands. The only disadvantage is that we need another way of initiating new Mern based projects.

`mkdir my_app && cd my_app`
`npm init && npm i mern-cli`
`mern app --withLifeCycle`

Something like this. By running `npm init` I can care for details like git repository, name, description, tags, private.

My thoughts.

**Comment by mayankchd** [comment]
@fibric, Thanks for your suggestions, I will try to look into it and maybe change it!

**Comment by mayankchd** [comment]
https://github.com/sindresorhus/ama/issues/17

**Comment by somus** [comment]
Now, `mern-cli` can clone variants of MERN project from various repositories which require it to be installed globally. For more details, visit Hashnode/mern-cli#10.
