### ISSUE TITLE
Unable to test  

### ISSUE THREAD

**Issue by ozkey** [Hashnode/mern-starter#201]
This issue related to:
[issue 198 ](https://github.com/Hashnode/mern-starter/issues/198)

related fix:
[fix](https://github.com/brandon-arnold/bacom-mern/commit/d16ad76b0496972df027eae790d9b99c9f2d7abe)

```
Error: proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag
```

to test in windows change `package.json` to:
`"test": "cross-env NODE_ENV=test PORT=8080 MONGO_URL=mongodb://localhost:27017/mern-test node_modules/.bin/nyc node_modules/.bin/ava --serial",`

to test in Mac change `package.json` to:
`
"test": "cross-env NODE_ENV=test PORT=8080 MONGO_URL=mongodb://localhost:27017/mern-test node_modules/.bin/nyc node --harmony-proxies node_modules/.bin/ava",`

**Comment by mannyhenri** [comment]
@MrChristofferson up to take a look at the test issues? This issue might be related to #250

**Comment by mattlubner** [comment]
The `--harmony-proxies` flag is no longer supported by Nodejs, and actually results in the test suite crashing immediately if passed. Removed in #367.
