### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by coldhiber** [Hashnode/mern-starter#203]
Guys, what do you think about using async/await on the server side (https://babeljs.io/docs/plugins/transform-async-to-generator/)?

I think this is the future of asynchronous programming in JS. We can potentially remove promise-resolving callbacks and switch to it.

I could integrate this. Thoughts?

**Comment by somus** [comment]
Yeah, async/await is awesome. It would be great if you could send a PR.

**Comment by coldhiber** [comment]
@somus great! Get started to work on this.

**Comment by wootsaejao** [comment]
Here we go #248.

**Comment by mattlubner** [comment]
Perhaps I've misunderstood the request, but it is already possible to use async/await on the server with the latest version of MERN.
