### ISSUE TITLE
Fresh npm install not working

### ISSUE THREAD

**Issue by xiaolin** [Hashnode/mern-starter#209]
did a fresh `npm install`, and ran into the error below when running `npm start`

```
Unexpected token (125:10)
  123 |       .then(() => {
  124 |         const initialView = renderToString(
> 125 |           <Provider store={store}>
      |           ^
  126 |             <IntlWrapper>
  127 |               <RouterContext {...renderProps} />
  128 |             </IntlWrapper>
```

**Comment by ishitakothari** [comment]
I am getting the same error. Is there any solution?

**Comment by fatman-** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;jbs3baFR&#x2F;9-fresh-npm-install-not-working"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fresh NPM install not working</a>

**Comment by tylerehc** [comment]
I am also getting this--any luck?

**Comment by Mihirmathur** [comment]
I'm having the same issue. How did you guys resolve it?

**Comment by kmenghini** [comment]
Having this issue currently - were you guys able to find a solution?
