### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by rdewolff** [Hashnode/mern-starter#21]
Have you thought about using GraphQL in MERN?

**Comment by sandeeppanda92** [comment]
This can be a good addition. Will be great if you can fork this repo and build a GraphQL server. In `mern-cli` we can pass a flag such as `mern <yourApp> --graphQL` which will clone the GraphQL based repo.

**Comment by jferrettiboke** [comment]
I agree. GraphQL is powerful and very flexible. It would be a very nice choice to implement on this stack.

**Comment by HaNdTriX** [comment]
I would love to see this in mern!

**Comment by AhmadEl-Banna** [comment]
+1

**Comment by somus** [comment]
Graphql is bit complex and may not be suitable for beginners. We want to keep this project beginner friendly. We are planning to create a separate project for advanced users in future.

**Comment by rajkapoordev** [comment]
@somus, Any update on support for GraphQL?
