### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by spijko** [Hashnode/mern-starter#210]
Hi,

I have a production ready mern app which I'm trying to load up on different browsers. It runs as expected in Chrome/Firefox but fails on IE 11 and below. Ideal situation would be to run it minimally on IE11, however I'm getting the following error 

> webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

Is MERN currently working on IE at all?

Thanks

**Comment by somus** [comment]
A polyfill needs to be added for the hot reloading to work in IE. I'll add it.

**Comment by somus** [comment]
Fixed in 2c49a05
