### ISSUE TITLE
Errors while running npm test

### ISSUE THREAD

**Issue by Nixhatter** [Hashnode/mern-starter#211]
Hey so I'm getting a strange error when trying to run **npm test** and I can't figure out why.

Here are the results:

> 32 passed
>    1 failed
>    1 rejection
> 
> 
>    1. server › models › post › Should correctly give number of Posts
>      
>   t.deepEqual(posts.length, res.body.posts.length)
>                     |                      |      
>                     2                      0      
>   
>       _callee$ (post.spec.js:33:5)
>     tryCatch (/home/nix/Documents/poke/node_modules/regenerator-runtime/runtime.js:62:40)
>     GeneratorFunctionPrototype.invoke [as _invoke] (/home/nix/Documents/poke/node_modules/regenerator-runtime/runtime.js:336:22)
>     GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/nix/Documents/poke/node_modules/regenerator-runtime/runtime.js:95:21)
>     _combinedTickCallback (internal/process/next_tick.js:67:7)
>     process._tickCallback (internal/process/next_tick.js:98:9)
> 
> 
>    2. Unhandled Rejection
>    ValidationError: Path `slug` is required.
>     MongooseError.ValidationError (/home/nix/Documents/poke/node_modules/mongoose/lib/error/validation.js:22:11)
>     model.Document.invalidate (/home/nix/Documents/poke/node_modules/mongoose/lib/document.js:1402:32)
>     /home/nix/Documents/poke/node_modules/mongoose/lib/document.js:1278:17
>     validate (/home/nix/Documents/poke/node_modules/mongoose/lib/schematype.js:701:7)
>     /home/nix/Documents/poke/node_modules/mongoose/lib/schematype.js:738:9
>     SchemaString.SchemaType.doValidate (/home/nix/Documents/poke/node_modules/mongoose/lib/schematype.js:706:19)
>     /home/nix/Documents/poke/node_modules/mongoose/lib/document.js:1276:9
>     _combinedTickCallback (internal/process/next_tick.js:67:7)
>     process._tickCallback (internal/process/next_tick.js:98:9)
> fs.js:584
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open '/home/nix/Documents/server.js'
>     at Error (native)
>     at Object.fs.openSync (fs.js:584:18)
>     at Object.fs.readFileSync (fs.js:431:33)
>     at LookupStore.Store.mix.get (/home/nix/Documents/poke/node_modules/nyc/node_modules/istanbul/lib/store/fslookup.js:40:19)
>     at HtmlReport.Report.mix.writeDetailPage (/home/nix/Documents/poke/node_modules/nyc/node_modules/istanbul/lib/report/html.js:411:67)
>     at /home/nix/Documents/poke/node_modules/nyc/node_modules/istanbul/lib/report/html.js:489:26
>     at SyncFileWriter.extend.writeFile (/home/nix/Documents/poke/node_modules/nyc/node_modules/istanbul/lib/util/file-writer.js:57:9)
>     at FileWriter.extend.writeFile (/home/nix/Documents/poke/node_modules/nyc/node_modules/istanbul/lib/util/file-writer.js:147:23)
>     at /home/nix/Documents/poke/node_modules/nyc/node_modules/istanbul/lib/report/html.js:488:24
>     at Array.forEach (native)
> npm ERR! Test failed.  See above for more details.

The slug error is an error that spawned from the latest commit, but I see that error on the Travis build so I'm not worried about it.
The other two messages are confusing me. 
For example, why is it looking in the the documents directory when the project is in "poke" folder, and the server.js file is in the server folder? 
"Error: ENOENT: no such file or directory, open '/home/nix/Documents/server.js'" 
The other error, where it's not returning the correct amount of posts is also confusing. When I do an npm start, the starter seems to load fine with the two dummy blog posts.

I'm running node v5.12.0, npm 3.8.6, MongoDB 3.0.12 on CentOS 7 with a brand new mern init (also just tried cloning the repo). I've tried npm cache clean, restarting and starting a new project.

**Comment by froskie** [comment]
In order to fix mine:

Updates on `package.json`:

```
dependencies: {
  ...,
  "nyc": "^7.1.0",
  "babel-plugin-istanbul": "^1.0.3",
},
nyc: {
  "require": [
    "babel-register"
  ],
  "sourceMap": false,
  "instrument": false
}
```

Updates on `.babelrc`:

```
"env": {
  "test": {
    "plugins": ["istanbul"]
  }
}
```

**Comment by Nixhatter** [comment]
Yeah that seems to have helped, thank you!
