### ISSUE TITLE
Unable to use @import

### ISSUE THREAD

**Issue by vizFlux** [Hashnode/mern-starter#223]
Hi, I've been trying to use @import to modularize the the css, but it is not working. I saw `importLoaders` is implemented in the webpack configs, but somehow not working.

**Comment by fatman-** [comment]
Refer to [this](https://hashnode.com/post/mern-import-css-files-cirvpqoqx0bj7nc5398tcy1hm/answer/cirw3mmwo0e1se5535vi3ges8) answer, for a solution.
