### ISSUE TITLE
[question] PostDetailPage container data reqs

### ISSUE THREAD

**Issue by KATT** [Hashnode/mern-starter#227]
Currently it's not possible to navigate to a `PostDetailPage` unless the item is already fully loaded in the state. This not a biggie in the example, but in an application where the detail page has more extensive data requirements than what's expected on the list page it would introduce errors.

Do you have any good pattern to ensure the `.need` of a `PostDetailPage` on the client? It would be nice to have a pattern similar to [`@asyncConnect`](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/containers/Widgets/Widgets.js#L10) that could be utilised on both server and client to ensure data reqs.

[makeomatic/redux-connect](https://github.com/makeomatic/redux-connect) looks like a good fork of the asyncConnect lib above.

**Comment by fatman-** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Kk0KYjDA&#x2F;7-question-on-postdetailpage"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Question on PostDetailPage</a>

**Comment by somus** [comment]
For the simplicity's sake, we made the example like that. But a real-world example should not load the whole data in the list API. Ideally, single post API should be either called in `componentWillMount` of the `PostDetailPage`, or it should be called before the route transition.
