### ISSUE TITLE
testing: Uncaught Error: listen EADDRINUSE :::8000

### ISSUE THREAD

**Issue by shangsunset** [Hashnode/mern-starter#23]
Hi,

I got this error running tests. i know its because the server is already running and `require(../server);`  in test file would start another server. but i dont know a way to avoid this.

because `server.js` is required by `index.js`. so checking `module.parent` before starting the server wont help here.

thank.

**Comment by prank7** [comment]
Thanks for raising this issue. This [commit ](https://github.com/Hashnode/mern-starter/commit/d4a8c43496e3c0da1671bba683258890c54c2212) fixes it.
