### ISSUE TITLE
In webpack.config.dev.js use localhost instead of 0.0.0.0

### ISSUE THREAD

**Issue by DraconPern** [Hashnode/mern-starter#232]
On windows (tested on 10), use publicPath: 'http://localhost:8000/', instead of publicPath: 'http://0.0.0.0:8000/'.  On line 26 of webpack.config.dev.js.  Shouldn't affect other platforms.

**Comment by u0078867** [comment]
Yes, also for me (Windows 7), it can give issues to the *HMR* runtime
