### ISSUE TITLE
Sourcemaps?

### ISSUE THREAD

**Issue by amygdaloideum** [Hashnode/mern-starter#236]
How is this supposed to work? When I get errors in the chrome console they all refer to minified code that webpack made. Do everybody experience this or am I doing something wrong?

**Comment by karolgorecki** [comment]
You can change in the `webpack.config.dev.js` the `devtool` param to `devtool: 'source-map',`

**Comment by amygdaloideum** [comment]
If anyone is facing the same problem I solved it by removing: `devtool: 'cheap-module-eval-source-map',` and instead added
 `new webpack.SourceMapDevToolPlugin({
     filename: '[file].map'
 })`

in webpack.config.dev.js
