### ISSUE TITLE
bundle.js not created in development mode

### ISSUE THREAD

**Issue by simran-k** [Hashnode/mern-starter#237]
1. My application starts with index.html served through express router
2. Next I need to enable react-router.My application entry point is client/index.js which looks like this:

```

/**
 * Client Entry Point;
 */

import 'babel-polyfill';  //certain functions like array.from , set, map can't be transpiled by babel so ue poyfill for that
import React from 'react';
import {  render } from 'react-dom';
import { Router, browserHistory } from 'react-router';
import  routes  from './routes';


render((
  <Router history={browserHistory} routes={routes}/>),
  document.getElementById('app')
);

console.log("In index js render ")

```

Above console statement is never consoled. It is set as entry point in webpack.dev.js . It should also output the bundled file app.js or bundle.js (whatever called in webpck config) but that never gets created. I believe I need to add that bundle file in index.html for react-routing to start thereafter?

I tried running `npm run bs` and the file server.bundle.js was created just fine in dist folder .Why is it not getting created in development mode?Also, why is react-router not working in this arrangement? Could I get some help on this please?

also, if I add a script tag in my index.html i.e

<script src="index.js></script>

It can't find it. No matter whatsoever js file I try to import here. It can't "see" it. resulting in an error: unexpected symbol <!DOCTYPE> from index.html. (!Doctype isn't the problem). It keeps giving the same error even when I take off Doctype and no matter which script file I try to import.

**Comment by mannyhenri** [comment]
Probably a bit delayed to answer this one, but a lot of this will change as we implement React Router V4 and webpack 4...so keep following our updates.
