### ISSUE TITLE
promiseUtils

### ISSUE THREAD

**Issue by export-mike** [Hashnode/mern-starter#238]
Thanks for the project I've been using this for a "universal app" I've been working on.

I've come across the sequence method you have in the [promiseUtils](https://github.com/Hashnode/mern-starter/blob/master/server/util/promiseUtils.js) I was just wondering why its written the way it is? from what I can see the following snippet below is doing what you need?

I'm asking more in the way of my own "understanding the code" and not suggesting any changes.

``` JavaScript
const items = [1,2,3]
const res = Promise.all(items.map(i => i * 2))
res.then((a) => console.log(a))
// Array [
//  2,
//  4,
//  6
// ]
```

**Comment by somus** [comment]
`Promise.all` doesn't execute in any particular order. Here, we need to ensure the promises are running sequentially. Because data loaded by one action might be required by another component down the chain. Let me know if this answers your question.

**Comment by export-mike** [comment]
That makes sense , thanks for your time
