### ISSUE TITLE
Isomorphic styles not working

### ISSUE THREAD

**Issue by jmsherry** [Hashnode/mern-starter#241]
Now, I might be wrong here, but I thought that the isomorphic function in server.js basically created html from generating a small instance of the react server and getting html from there. It would also gather the relevant CSS and inject it, so that your page would be delivered to the client with complete HTML & CSS, and no client side rendering would take place(?!).

With Javascript switched off on the client, it fails. I get the following from a vanilla install:

**HTML** (abbreviated)

```
<!doctype html>
    <html>
      <head>
        
        <title data-react-helmet="true">MERN Starter - Blog App - Blog App</title>
        <meta data-react-helmet="true" charset="utf-8"/><meta data-react-helmet="true" http-equiv="X-UA-Compatible" content="IE=edge"/><meta data-react-helmet="true" name="viewport" content="width=device-width, initial-scale=1"/>
        
        

        <link rel='stylesheet' href='/app.3244828b0515522d2dc4.css' />
        <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700' rel='stylesheet' type='text/css'/>
        <link rel="shortcut icon" href="http://res.cloudinary.com/hashnode/image/upload/v1455629445/static_imgs/mern/mern-favicon-circle-fill.png" type="image/png" />
      </head>
      <body>
        <div id="root">
<div data-reactroot="" data-reactid="1" data-react-checksum="-747348766">
<div data-reactid="2">
<!-- react-empty: 3 -->
<div class="Header__header__2sEZY" data-reactid="4"><div class="Header__language-switcher__3bviQ" data-reactid="5"><ul data-reactid="6"><li data-reactid="7"><span data-reactid="8">Switch Language</span></li><li class="Header__selected__3IRlm" data-reactid="9">en</li>
```

**CSS** (abbreviated)
`._4uEyKcd5WHob5qPzotT7{max-width:980px;width:100%;padding:15px;margin:0 auto}._2sEZYfHlvDy9uXqVIXG1aM{background:#eee url(/bbaeb5f32b7042f0def39648a1d111b9.png) 50%;background-size:cover;border-bottom:1px solid #ccc}._1eavAvnySzoZc5rld6Q4pa{width:100%;max-width:980px;margin:auto;padding:64px 16px;overflow:auto}.UfFn6muOcOBjkVI5_yltp{font-weight:300;font-size:42px;float:left}.CkTz6a2gQTJjwXIEAlTSk,.UfFn6muOcOBjkVI5_yltp a{text-decoration:none;color:#fff}.CkTz6a2gQTJjwXIEAlTSk{display:inline-block;background:#03a9f4;padding:8px 16px;border-radius:1000px;float:right}._3bviQya5ZWCvWr6lGdfO9h{background:rgba(0,0,0,.1)}`

If you look at the header, it gets a class of 'Header__header__**2sEZY**' and if you look in the css you can see '._**2sEZY**fHlvDy9uXqVIXG1aM' is the corresponding style definition.

Is this a webpack issue??

**Comment by fatman-** [comment]
This has been fixed, refer to [this](https://github.com/Hashnode/mern-starter/commit/fec16f5780cd7a04872ae1d50ed6899baadee019) diff, for the fix. 

Thanks for identifying this, @jmsherry :)

**Comment by jmsherry** [comment]
@fatman- No probs. Great job on a quick fix! 👍
