### ISSUE TITLE
Import external module stylesheets

### ISSUE THREAD

**Issue by gilles-yvetot** [Hashnode/mern-starter#243]
Hello everyone,

First thing, awesome job with the boilerplate, I am new to the MERN stack and it allows me to learn very important and complex concepts of it without being too complicated. Thank you for this.

I am trying to use [another module](https://github.com/davidchin/react-input-range) within my mern projet. I installed it via npm and tried to import the default style like instructed. Everything works except the fact that no style is imported. I tried to import/require the stylesheet present in the node_modules, then tried to copy it into my component folder and then import/require it, but still no results.

I thought webpack (with css-loader, style-loader and postcss) will auto import the css within my component like it is done with `require("./main.css")` but no :(

Am I missing a step or anything, or maybe this is not working with the component I want to use.

**Comment by somus** [comment]
How did you import the css? Also, see the bundle css to check whether it has the imported css?

**Comment by gilles-yvetot** [comment]
Yep, the CSS was imported, the problem was with the plugin I was trying to use, I had to copy the stylesheet from the node modules to my component folder and then map the className generated by the webpack loader with an attribute classNames.

```
import styles from './DoubleSlider.css'
const classNames = {
	component: styles['InputRange'],
	labelContainer: styles['InputRange-labelContainer'],
	labelMax: styles['InputRange-label'] + ' ' + styles['InputRange-label--max'],
	labelMin: styles['InputRange-label'] + ' ' + styles['InputRange-label--min'],
	labelValue: styles['InputRange-label'] + ' ' + styles['InputRange-label--value'],
	slider: styles['InputRange-slider'],
	sliderContainer: styles['InputRange-sliderContainer'],
	trackActive: styles['InputRange-track'] + ' ' + styles['InputRange-track--active'],
	trackContainer: styles['InputRange-track'] + ' ' + styles['InputRange-track--container'],
};
<InputRange minValue=classNames={classNames} />
```
