### ISSUE TITLE
react's module size is about 605.33 KB (18.6%) in webpack analyser.

### ISSUE THREAD

**Issue by kishanj918** [Hashnode/mern-starter#244]
when i  was analysing my webpack modules, it's showing me react's stats as following.
react: 605.33 KB (18.6%).
I had tried importing react modules  as import React from 'react/lib/React' but that didn't help to reduce size. Why this much size? Any way we can reduce it?

**Comment by somus** [comment]
One shown there is development version of react. That is the reason for the big size. In production build, the size will be much lesser.

**Comment by kishanj918** [comment]
i guess this is for production build. I have ran the following command.  
webpack --config webpack.config.prod.js --json | webpack-bundle-size-analyzer > stats.txt

is there something i am doing wrong?

**Comment by somus** [comment]
> The statistics reported for modules in Webpack's JSON output do take into account transformations resulting from loaders, but not plugins which operate on the whole generated bundle.
>
> The recommended approach to minifying JavaScript in Webpack bundles is to use the UglifyJS plugin, which operates on the whole bundle. Consequently, the stats shown by webpack-bundle-size-analyzer will report sizes before minification. This should still give a pretty good idea of what contributes to your bundle size, but some libraries will compress better than others so that they can be misleading.
>
> A workaround is to generate a Webpack build using the [UglifyJS loader](https://www.npmjs.com/package/uglify-loader) instead and use the JSON output from that. Since the loader runs on individual files before they are bundled, the accounting will be correct.

> -*Taken from webpack-bundle-size-analyzer documentation.*

Let me know if this helps.

**Comment by kishanj918** [comment]
I'll try. Thanks.
