### ISSUE TITLE
Store components as .jsx files

### ISSUE THREAD

**Issue by bencevans** [Hashnode/mern-starter#25]
Storing the JSX files such as `/shared/components/Header/Header.js` as `.jsx` files would help pickup the format for linters, and editors.

**Comment by SOSANA** [comment]
1+

**Comment by beaucharman** [comment]
+1

**Comment by rstuven** [comment]
+1

**Comment by msell** [comment]
+1

**Comment by rmundy** [comment]
+1

**Comment by prank7** [comment]
@bencevans @SOSANA @beaucharman @rstuven @msell @rmundy   Sure, this is a very good. Would be great if anyone of you could send a PR fixing this.

**Comment by beaucharman** [comment]
Addressed in https://github.com/Hashnode/mern-starter/pull/34

**Comment by mayankchd** [comment]
Thanks @beaucharman!
