### ISSUE TITLE
Slow rebuild times

### ISSUE THREAD

**Issue by shankiesan** [Hashnode/mern-starter#255]
I'm new to MERN, but totally ❤️  this project.

I'm having one issue however – very slow rebuild times on the server-side code. It's about 30 seconds when using `npm start` and 2 minutes using Docker for Mac (which has recognised issues with file system performance, so it's not surprising that that takes a bit longer).

What kind of build times is everyone else experiencing? This is on a 4-year old MBP; however, I'm still surprised that it's so slow – my normal React package webpack re-builds are in the order of 5 seconds.

**Comment by kfrankovic** [comment]
This is the same issue as this one [https://github.com/Hashnode/mern-starter/issues/186](url)

But to answer the question, we are currently on almost 3 minutes for build times. And it doesn't get any better on fast machines (quad i7 6700k with 32 GB of RAM).

**Comment by shankiesan** [comment]
Good spot @kfrankovic . I'll close this issue.

**Comment by terenzeyuen** [comment]
Issue 186 is not available anymore?

**Comment by kfrankovic** [comment]
From some reason link in my original post is not ok (it adds url at the end so it looks like issues/url...), change that url to 186 or just copy the link. Weird.

**Comment by terenzeyuen** [comment]
Ok cool – did you found a fix? Still very slow startup or restart for us.

**Comment by kfrankovic** [comment]
Yes, please take a look at original post.

**Comment by terenzeyuen** [comment]
Doesn't seem to have effect on us.
