### ISSUE TITLE
Server-side rendering vs client side

### ISSUE THREAD

**Issue by gilles-yvetot** [Hashnode/mern-starter#257]
Hello,

I have worked with the mern starter during a couple of weeks now (awesome job), and I am not able to answer my own question about the server side rendering.

I have published my website to heroku, but what I meant by publication is everything (client+server). From what I understood, it means the server is installing the nodes_modules and then build the `dist` folder and serve it, but every time I go on my heroku app in my browser, the node server runs `index.js` that runs `./dist/server.bundle.js` (which is `server/server.js` compiled if I understand correctly). But this file is always performing server-side rendering (for the routes that are not matched by the api routes), so how can I serve my react app without server side rendering ?

I know it seems like a noob question but I am missing a point for sure :(

**Comment by iamsolankiamit** [comment]
You should build the server locally and upload it on heroku, then change the proc file to run `npm start:prod`

**Comment by gilles-yvetot** [comment]
So far I was pushing the entire project and then specified: 
`"heroku-postbuild": "npm run clean && npm run build && npm run build:server"` in my package.json scripts.

But I think your idea is better yes. But my question was more about the rendering. When is the server rendering and when is the client rendering?

**Comment by iamsolankiamit** [comment]
Server Side rendering happens the first time you load the page, subsequent request are handled by client side rendering.

**Comment by gilles-yvetot** [comment]
thanks buddy, everything makes more sense now
