### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by ishita-kothari** [Hashnode/mern-starter#261]
Hello team,

When I copy my project, install modules fresh and try to start my project, I have issue stating:
SyntaxError: /server/server.js: Unexpected token (122:10)
  120 |       .then(() => {
  121 |         const initialView = renderToString(
> 122 |           <Provider store={store}>
      |           ^
  123 |               <RouterContext {...renderProps} />
  124 |           </Provider>
  125 |         );

How can I resolve this issue? I don't want to clone the boilerplate and try for the project. I want to work with the copy of my project.

**Comment by iamsolankiamit** [comment]
Can you be more specific on what the issue is? It might possibly be that you haven't run `npm install` yet.

**Comment by iamsolankiamit** [comment]
Can you be more specific on what the issue is? did you clone the repo? is it a fresh installation? It might possibly be that you haven't run npm install yet.

**Comment by RPComp** [comment]
I have cloned the project already built in mern. I have installed modules and when I run command npm start, I get the following error:

SyntaxError: mern/server/server.js: Unexpected token (123:10)
  121 |       .then(() => {
  122 |         const initialView = renderToString(
> 123 |           <Provider store={store}>
      |           ^
  124 |             <IntlWrapper>
  125 |               <RouterContext {...renderProps} />
  126 |             </IntlWrapper>

Can you please help me out?
