### ISSUE TITLE
React warning on first time npm start

### ISSUE THREAD

**Issue by cocacrave** [Hashnode/mern-starter#263]
After initial npm start I'm getting this warning in browser console.
```
VM28315:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot="
```

**Comment by tapesec** [comment]
Look at the end of the readme.md

Client and Server Markup Mismatch

This warning is visible only on development and totally harmless. This occurs to hash difference in react-router. To solve it, react router docs asks you to use match function. If we use match, react-hot-reloader stops working.

**Comment by hhlevnjak** [comment]
There is a workaround to make the warning go away, as explained here #149
