### ISSUE TITLE
windows 10 error when do `npm install`

### ISSUE THREAD

**Issue by adamchenwei** [Hashnode/mern-starter#268]
Whole bunch of error. Do not know what to do next since i do not want to just randomly guess and install things.... Attached the error displayed

> C:\wamp\www\mern-starter>npm install
> npm WARN peerDependencies The peer dependency webpack@^1.4.0-beta6 included from chunk-manifest-webpack-plugin will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> npm WARN peerDependencies The peer dependency webpack@>=1.12.9 <3.0.0 included from babel-plugin-webpack-loaders will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> npm WARN peerDependencies The peer dependency webpack@^1.9.11 included from extract-text-webpack-plugin will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> npm WARN peerDependencies The peer dependency webpack@^2.1.0-beta.26 included from webpack-dev-server will no
> npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
> npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
> npm WARN optional dep failed, continuing fsevents@1.0.15
> npm WARN optional dep failed, continuing fsevents@1.0.15
> npm WARN deprecated node-uuid@1.4.7: use uuid module instead
> npm WARN optional dep failed, continuing fsevents@1.0.15
> 
> > spawn-sync@1.0.13 postinstall C:\wamp\www\mern-starter\node_modules\pre-commit\node_modules\cross-spawn\node_modules\spawn-sync
> > node postinstall
> 
> 
> > spawn-sync@1.0.15 postinstall C:\wamp\www\mern-starter\node_modules\mockgoose\node_modules\mongodb-prebuilt\node_modules\spawn-sync
> > node postinstall
> 
> 
> > pre-commit@1.1.3 install C:\wamp\www\mern-starter\node_modules\pre-commit
> > node install.js
> 
> \pre-commit:
> pre-commit: Failed to symlink the hook file in your .git/hooks folder because:
> pre-commit: EPERM: operation not permitted, symlink '..\..\node_modules\pre-commit\hook' -> 'C:\wamp\www\mern-starter\.git\hooks\pre-commit'
> pre-commit: The hook was not installed.
> pre-commit:
> npm WARN optional dep failed, continuing fsevents@1.0.15
> 
> > mongodb-prebuilt@5.0.8 postinstall C:\wamp\www\mern-starter\node_modules\mockgoose\node_modules\mongodb-prebuilt
> > node install.js
> 
> done
> inside extract, run complete 145.1mb)
> Done installing MongoDB
> 
> > nodejieba@1.4.11 install C:\wamp\www\mern-starter\node_modules\limax\node_modules\pinyin\node_modules\nodejieba
> > node-gyp rebuild
> 
> 
> C:\wamp\www\mern-starter\node_modules\limax\node_modules\pinyin\node_modules\nodejieba>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
> gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
> gyp ERR! System Windows_NT 10.0.14393
> gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\wamp\www\mern-starter\node_modules\limax\node_modules\pinyin\node_modules\nodejieba
> gyp ERR! node -v v4.5.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm WARN optional dep failed, continuing nodejieba@1.4.11
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v4.5.0
> npm ERR! npm  v2.15.9
> npm ERR! path C:\Users\chenw_000\AppData\Roaming\npm-cache\diff-match-patch\1.0.0\package.tgz.3533495900
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall rename
> 
> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\chenw_000\AppData\Roaming\npm-cache\diff-match-patch\1.0.0\package.tgz.3533495900' -> 'C:\Users\chenw_000\AppData\Roaming\npm-cache\diff-match-patch\1.0.0\package.tgz'
> npm ERR!     at Error (native)
> npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\chenw_000\AppData\Roaming\npm-cache\diff-match-patch\1.0.0\package.tgz.3533495900' -> 'C:\Users\chenw_000\AppData\Roaming\npm-cache\diff-match-patch\1.0.0\package.tgz']
> npm ERR!   errno: -4048,
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'rename',
> npm ERR!   path: 'C:\\Users\\chenw_000\\AppData\\Roaming\\npm-cache\\diff-match-patch\\1.0.0\\package.tgz.3533495900',
> npm ERR!   dest: 'C:\\Users\\chenw_000\\AppData\\Roaming\\npm-cache\\diff-match-patch\\1.0.0\\package.tgz',
> npm ERR!   parent: 'power-assert-renderer-comparison' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\wamp\www\mern-starter\npm-debug.log
> 
> C:\wamp\www\mern-starter>

**Comment by adamchenwei** [comment]
an here is npmdebug log
https://drive.google.com/file/d/0B2WmE5G9C09hN0hSNEh0WUhBX0U/view?usp=sharing

**Comment by adamchenwei** [comment]
Thought?

**Comment by hhlevnjak** [comment]
You will need to install Python.

But if you look at the error stack, MERN is referencing limax for generating url slugs, which depends on pinyin, which then depends on nodejiba for parsing Chinese characters. So you might not even need it.

**Comment by adamchenwei** [comment]
gotcha.... strange thing. maybe because I am on windows10 thats why no python...

**Comment by autukill** [comment]
@adamchenwei 
Pythoy is a third-party software, not built-in

**Comment by andrewsav-datacom** [comment]
Same error even with Python installed:

```
gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.EXE", you can set the PYTHON env variable.
```

Of course there *is* `C:\Python36\python.EXE` and it's completely functional.
