### ISSUE TITLE
MongoDB running, can't find it to connect to it on start

### ISSUE THREAD

**Issue by grimunit** [Hashnode/mern-starter#270]
Tried looking for this issue and wasn't able to see one where Mongo was actually running and people were getting errors.

Basically the app keeps erroring out on `npm start` saying the message you get if Mongo isn't running. I have it running on port 27017 and was able to open a mongo shell to it and issue commands. I don't have anything else running on port 8000 (also tried changing the port and re running), and I tried several other things like deleting the mongod.lock file and restarting.

Any other suggestions from anybody? Don't have a ton of experience using mongodb, so I may be missing something simple.

**Comment by MincePie** [comment]
Did you figure this out. I'm stuck in the same position

**Comment by mannyhenri** [comment]
Try the comments on issue #152
