### ISSUE TITLE
Is exposing server.bundle.js a bad idea? 

### ISSUE THREAD

**Issue by jospablos** [Hashnode/mern-starter#271]
The starter serves the whole /dist folder, which means that anyone can access the server.bundle.js file. Is that a bad idea? 

Given that you take care of basic security things like not exposing secret keys and such, would exposing the transpiled and bundled server code put the app security at risk in any way? Or is it just a matter of whether you care or not that it is visible?

**Comment by hhlevnjak** [comment]
I feel this is a really big issue, even if you take care not to store any sensitive data like secret keys directly in your code, you still don't want anyone to be able to know all of the inner workings of your code and possibly take advantage of any weakness.

The simplest way to fix this is simply to move the sever.bundle.js file out of the dist directory in the server webpack configuration, and of course require it from it's new location in index.js.

**Comment by somus** [comment]
This has been fixed in 14666d2c6d81e8ced13cc50985cd73bcc03ca5ce. Only client bundles and files are exposed through express now.
