### ISSUE TITLE
Error: listen EADDRINUSE :::8080

### ISSUE THREAD

**Issue by andrefox333** [Hashnode/mern-starter#279]
Hi everyone :) Quick question, how can I add more tests that need to connect to DB similar to the model/post.spec.js? 

I keep getting a 
```
 1. Uncaught Exception
   Error: listen EADDRINUSE :::8080
    Object.exports._errnoException (util.js:1026:11)
    exports._exceptionWithHostPort (util.js:1049:20)
``` 
every time I try to add a new spec file that has the code below in it.
```
test.beforeEach('connect to database', t => {
  connectDB(t, () => {
    console.log('connected to DB for account tests');
  });
});

test.afterEach.always(t => {
  dropDB(t);
});
```

Any suggestions/ideas? Thank you :)

**Comment by andrefox333** [comment]
Anyone?

**Comment by Fallenstedt** [comment]
EADDRINUSE means that the port number which listen() tries to bind the server to is already in use.

So, in your case, there must be running a server on port 8080 already.

**Comment by panvourtsis** [comment]
anyone fixed this?

**Comment by Fallenstedt** [comment]
@panvourtsis  literally read this https://github.com/Hashnode/mern-starter/issues/279#issuecomment-287099746

**Comment by panvourtsis** [comment]
@Fallenstedt yes i know what it means. The thing is that when you got more than one test in place for the models this happens in whatever port you define. It just starting the next test without closing the usage of the port. Tried 8080, 4350, 6565 etc etc always the same

**Comment by drewbrend** [comment]
@panvourtsis I know this is over a year late, but I just ran into this issue and solved it.  The tests are running in parallel and both trying to spin up a DB.  You need to run them serially by adding the `--serial` flag to the tests command in `package.json`.

```
    "test": "cross-env NODE_ENV=test PORT=8000 MONGO_URL=mongodb://localhost:27017/test-results node_modules/.bin/nyc node node_modules/ava/cli.js --serial",
```

Hopefully that helps someone else.
