### ISSUE TITLE
Where's the index.html?

### ISSUE THREAD

**Issue by cbll** [Hashnode/mern-starter#281]
I'm learning the MERN stack now and got the server running at localhost:8000 - where is the index.html I can see in developer tools? I can follow the flow with App.js and webpack compiling it. But if I want to create more modules, I need to "input them" somewhere - in the index.html. But I can't seem to locate it?

**Comment by ForsakenHarmony** [comment]
why would you want to input anything into the index html except for the bundle?

**Comment by ctalladen78** [comment]
Welcome to ES6 and Webpack
