### ISSUE TITLE
Will project be maintained?

### ISSUE THREAD

**Issue by pgrekovich** [Hashnode/mern-starter#288]
Will project be maintained? Can i use it in production?

**Comment by spaceneenja** [comment]
Looks like no. Why create a project simply to abandon it without at least doing the community the courtesy of taking it down? MEAN stack has been idle for 2 years now. I wish I knew why these projects keep getting abandoned.

**Comment by spaceneenja** [comment]
Talk is cheap, commits speak volumes. Use in production if you're willing to maintain it yourself.

**Comment by jgautheron** [comment]
@pgrekovich I wouldn't recommend using this boilerplate for a new project. This boilerplate is outdated and contains many issues that could only be fixed with a deep rewrite.

**Comment by pgrekovich** [comment]
@jgautheron thanks mate!
