### ISSUE TITLE
received couple warning. 

### ISSUE THREAD

**Issue by mtndew1** [Hashnode/mern-starter#292]
Can someone tell me what I am missing and what should I do for it. I tried to npm start it but I got message saying app crushed. 

npm WARN chunk-manifest-webpack-plugin@0.1.0 requires a peer of webpack@^1.4.0-beta6 but none was installed.
npm WARN babel-plugin-webpack-loaders@0.7.1 requires a peer of webpack@>=1.12.9 <3.0.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN webpack-dev-server@2.4.2 requires a peer of webpack@^2.2.0 but none was installed.

Thank you

**Comment by Chathula** [comment]
what is your node and npm version? 

have you installed webpack locally? if not try it!

**Comment by mtndew1** [comment]
Thank you for helping me out.
