### ISSUE TITLE
Any Plan to include Vue.js

### ISSUE THREAD

**Issue by techjewel** [Hashnode/mern-starter#293]
MERN looks awesome. I wanted to know if you guys have any plan to include vuejs so devs can choose either React or VueJS. The Vue community is growing.

**Comment by carloscuatin** [comment]
nice 👍

**Comment by jrburke2** [comment]
This would be ideal if Vue keeps gaining traction.

**Comment by mannyhenri** [comment]
Not at this point. Focusing on React for the time being.
