### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by damiansilbergleithcunniff** [Hashnode/mern-starter#295]
Is there any plan to assemble some documentation on how to use this project?  I spent a while doing [this tutorial](https://hashnode.com/post/react-tutorial-using-mern-stack-ciiyus9m700qqge53mer0isxz) but it wasn't enough for me to understand this project.  In the end I had to abandon mern.io and switch to the tech-dojo mern project.  That project had ample documentation and I was up and running fairly quickly.

It's clear to me that this project is more robust and well structured, but without documentation explaining what the various parts of the system are and how they work together it's very difficult to get started. 

I'm hoping, once I fully understand the mern stack through tech-dojo, that I can return here, master mern.io, and produce some documentation.  But I have to figure that somebody is using this project, knows how it works, and can help write a 'getting started' guide that has more detail than the one we currently have.

Any takers?

**Comment by mannyhenri** [comment]
Yes we will update readme as we move towards V3.0....
