### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by TeodorKolev** [Hashnode/mern-starter#304]
In ever load I see html before css which is not cool at all. Must be fixed

**Comment by peterpetre** [comment]
Hi again, this is an issue happening only on development, i dont remember exactly why, it was some time ago that i was trying out this repo. Maybe if you search a bit on the issues you ll find it. But on production is fine!

**Comment by peterpetre** [comment]
Here you go :) [#161](https://github.com/Hashnode/mern-starter/issues/161)

**Comment by peterpetre** [comment]
Hi again, read this [caveats](https://github.com/Hashnode/mern-starter#caveats),  [#161](https://github.com/Hashnode/mern-starter/issues/161)
