### ISSUE TITLE
Hot reloading takes too much time

### ISSUE THREAD

**Issue by HaiderMalik12** [Hashnode/mern-starter#307]
Hot reloading takes too much time. When i change any file on server it takes two or three minutes to reload the content and start server again

**Comment by enginaryum** [comment]
Same here, already tried some isomorphic webpack packages to transpile seperately but couldn't succeed yet.

**Comment by mannyhenri** [comment]
@mattlubner I suspect with the udpated webpack we don't have this issue anymore, did you see differently?

**Comment by mattlubner** [comment]
This strikes me as a possible duplicate of #153 ?

**Comment by mannyhenri** [comment]
@mattlubner yes it is...closing
