### ISSUE TITLE
Image Won't Load

### ISSUE THREAD

**Issue by deathgaze** [Hashnode/mern-starter#313]
MERN starter looks like it includes an image on the main page. However, this image refuses to load. It looks like the page is trying to load it from, in my case, `http://0.0.0.0:8000/bbaeb5f32b7042f0def39648a1d111b9.png`. The image that appears not to load is `header-bk.png`.  If I visit `http://localhost:8000/bbaeb5f32b7042f0def39648a1d111b9.png` in my browser, it appears to work correctly, so for some reason the bundler is inserting the wrong host. Anyone know how to fix this?

**Comment by deathgaze** [comment]
I found that by changing the value of the `publicPath` variable in `webpack.config.dev.js` is enough to get rid of this issue. Is this intended?

**Comment by Jakku7** [comment]
What did you change the `publicPath` variable to?

**Comment by thrash4life** [comment]
@Jakku7 - Change the public path to the domain (even if it's localhost) where you are hosting your app. Don't forget to use the correct protocol http/https and use the correct port.

**Comment by liuzhiyuan1993** [comment]
edit your webpack.config.dev.js:

```javascript
// publicPath: 'http://0.0.0.0:8000/',
publicPath: 'http://localhost:8000/',
```
