### ISSUE TITLE
MERN Starter Blog Web App not working in IE 11

### ISSUE THREAD

**Issue by gameboyzone** [Hashnode/mern-starter#314]
Hello,

When I did a 'npm install' it worked fine but I did see few warnings on webpack v2.1.0-beta.8 in the command console in Windows 7. The MERN Starter Blog Web App works fine in Chrome  and Firefox, but it fails to works in IE 11 with 'Unknown browser' error in console. See console output below -

![capture](https://user-images.githubusercontent.com/3680631/26995818-8967069e-4d34-11e7-8a08-a57fd558e942.PNG)

PS: Mind you I have an updated package.json which was updated as per Issue #210  by @somus

**Comment by mannyhenri** [comment]
closed due to duplicated (and fixed) issue.
