### ISSUE TITLE
[Question] calling `new Express()`

### ISSUE THREAD

**Issue by chris-fa** [Hashnode/mern-starter#315]
Hey guys, nice stack you got here. I'm very interested in this one line of code, on your `server/server.js` file:

```js
const app = new Express();
```

I've always seen express called without the `new` keyword so I'm wondering why do you guys call it that way, and whether it can be done by default or you did something behind scene so you can call it with new keyword, or any other story behind it.

It's just a silly question I know, but I find it interesting.

Greetings!

**Comment by mannyhenri** [comment]
Just leveraging the ES6 class syntax in this case
