### ISSUE TITLE
Error after fresh isntall

### ISSUE THREAD

**Issue by JeffWScott** [Hashnode/mern-starter#321]
I have the worst luck with these pre-made packages!  I'm just trying to install this so I get get some tutorials run.  It's such an up hill battle when you have no idea about the different pieces of software that make this stuff work.  The little node stuff I have done so far is just a straight node server with maybe some extra stuff.  Nothing this involved.  I thought that the purpose of these npm was that it would take care of all the dependencies; but maybe I'm mistaken!

Anyway, frustration aside, this was my attempt to get this all setup and where it failed.

Created a fresh container of Ubuntu 14.04:
Installed
npm 2.15.11 and node 4.8.4
Then ran the install instructions from this site.
git clone https://github.com/Hashnode/mern-starter.git
    cd mern-starter
    npm install
    npm start

**During the npm install I got these warnings:**
pm WARN peerDependencies The peer dependency webpack@1 || 2 || 3 included from webpack-manifest-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@^1.4.0-beta6 included from chunk-manifest-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@>=1.12.9 <3.0.0 included from babel-plugin-webpack-loaders will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@^1.0.0 || ^2.0.0 || ^3.0.0 included from webpack-dev-middleware will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@^1.9.11 included from extract-text-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency caniuse-db@^1.0.30000652 included from postcss-cssnext will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@^2.2.0 || ^3.0.0 included from webpack-dev-server will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**During npm start I get this Error:**
npm ERR! Linux 2.6.32-042stab112.15
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mern-starter@2.0.0 start: `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mern-starter@2.0.0 start script 'cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js'.
npm ERR! This is most likely a problem with the mern-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mern-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mern-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cabox/workspace/mern-starter/npm-debug.log

**Comment by kidchenko** [comment]
The same here, the `npm install` until runs, but I think that the dependencies are obsolete and the hot-module-reload is not working.

**Comment by mannyhenri** [comment]
Thanks for reporting this issue, we're working on a new version V2.5.0 #330 that will fix any or all current issues. In the meantime if you want make absolutely sure you don't get the latest version of the dependencies remove the `^` before any package versions in package.json.. ex.: `"mockgoose": "^6.0.3"` to `"mockgoose": "6.0.3"`
