### ISSUE TITLE
Errors in getting started - configuration changes

### ISSUE THREAD

**Issue by MincePie** [Hashnode/mern-starter#322]
I have just tried to get started with this starter kit. I get 2 warnings and 2 errors - both seem to be fundamental. The warnings appear to be from changes in react since this starter kit was written. I'm trying to make sense of the errors. 

Has anyone encountered and resolved these?

> lowPriorityWarning.js?d93c:40 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
> printWarning @ lowPriorityWarning.js?d93c:40
> lowPriorityWarning @ lowPriorityWarning.js?d93c:59
> get @ React.js?24ef:108
> (anonymous) @ RouterContext.js?7ae9:43
> (anonymous) @ app.js:389
> __webpack_require__ @ vendor.js:558
> fn @ vendor.js:100
> (anonymous) @ Router.js?cf42:29
> (anonymous) @ app.js:3328
> __webpack_require__ @ vendor.js:558
> fn @ vendor.js:100
> (anonymous) @ index.js?e07d:39
> (anonymous) @ app.js:403
> __webpack_require__ @ vendor.js:558
> fn @ vendor.js:100
> (anonymous) @ App.js?85c4:6
> (anonymous) @ app.js:412
> __webpack_require__ @ vendor.js:558
> fn @ vendor.js:100
> (anonymous) @ index.js?8956:7
> (anonymous) @ app.js:1334
> __webpack_require__ @ vendor.js:558
> fn @ vendor.js:100
> (anonymous) @ app.js:3773
> __webpack_require__ @ vendor.js:558
> webpackJsonpCallback @ vendor.js:21
> (anonymous) @ app.js:1
> warning.js?8a56:35 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) <!-- react-empty: 1 -
>  (server) <div data-reactroot="
> printWarning @ warning.js?8a56:35
> warning @ warning.js?8a56:59
> _mountImageIntoNode @ ReactMount.js?26a9:507
> mountComponentIntoNode @ ReactMount.js?26a9:112
> perform @ Transaction.js?f15f:143
> batchedMountComponentIntoNode @ ReactMount.js?26a9:126
> perform @ Transaction.js?f15f:143
> batchedUpdates @ ReactDefaultBatchingStrategy.js?e9be:62
> batchedUpdates @ ReactUpdates.js?8e6b:97
> _renderNewRootComponent @ ReactMount.js?26a9:319
> _renderSubtreeIntoContainer @ ReactMount.js?26a9:401
> render @ ReactMount.js?26a9:422
> (anonymous) @ index.js?8956:14
> (anonymous) @ app.js:1334
> __webpack_require__ @ vendor.js:558
> fn @ vendor.js:100
> (anonymous) @ app.js:3773
> __webpack_require__ @ vendor.js:558
> webpackJsonpCallback @ vendor.js:21
> (anonymous) @ app.js:1
> client.js?3ac5:67 [HMR] connected
> (index):1 GET http://localhost:8000/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING
> client.js?3ac5:67 [HMR] connected

**Comment by Master244** [comment]
Having the same problem node version 9 fresh install
