### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by MincePie** [Hashnode/mern-starter#323]
Is this correct syntax for creating classes in react?

`export class PostCreateWidget extends Component {
`

I'm trying to reconcile this syntax with the advice in this document. https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

I can't make sense of how this starter app is conforming to the react documentation.

**Comment by jvitela** [comment]
Check here:
https://facebook.github.io/react/docs/components-and-props.html#functional-and-class-components
