### ISSUE TITLE
Question: My example starter render in the first time twice 

### ISSUE THREAD

**Issue by shmulikkaminker** [Hashnode/mern-starter#325]
Maybe someone can help me: I start playing with the mern starter project. in the componentWillMount function App.js file I added a function that checks if the user is login or not.

When i run the project on heroku instance i notice that the page renders twice in the first load.
The page renders and then disappears for a second and reappears.

What can be the problem? Here is the link for the production app:

https://stormy-mountain-23652.herokuapp.com

**Comment by mannyhenri** [comment]
Unable to check this one, closing.
