### ISSUE TITLE
Dispatch before App renders

### ISSUE THREAD

**Issue by shmulikkaminker** [Hashnode/mern-starter#328]
I try to set the user default language by a cookie in the server. What is the best way to get the cookie on each request from the server? may be set the state in server.js with the current lang?

**Comment by mannyhenri** [comment]
Best practices around setting languages is to use sessionstorage or localstorage on the client. Cookies aren't the best and safest way to do this anymore. This API is also much better to work with. https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#Storing_simple_data_%E2%80%94_web_storage
