### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by sbmadhav** [Hashnode/mern-starter#330]
Since React 16 moved to MIT license, would like to try this out, when you move to React 16.

**Comment by kamish24six** [comment]
+1

**Comment by PaulRBerg** [comment]
+1

**Comment by isaacjohnsononline** [comment]
+1

**Comment by SherlockStd** [comment]
+1

**Comment by InamTaj** [comment]
It seems this boilerplate has been abandoned.

**Comment by mmind-hub** [comment]
+1

**Comment by gal1419** [comment]
+1

**Comment by mannyhenri** [comment]
Everyone who is following this issue, we are working on it for version 2.5...

**Comment by mannyhenri** [comment]
We're looking at a PR #289 to upgrade to React 16.
