### ISSUE TITLE
User navigator local

### ISSUE THREAD

**Issue by shmulikkaminker** [Hashnode/mern-starter#335]
I'm trying to build a web application with support in 2 languages, with react-Intl .

The problem is that when I initial load from the server I do not have the user's browser language so I can not determine which language to display. I want to check it out in IntlReducerstate but I do not have access to Navigator of course because it's a load from the server.

What do you suggest?

**Comment by mannyhenri** [comment]
You get it from your React client side application and following the usual navigator.language property http://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language
