### ISSUE TITLE
it seems 'npm install' on node 8.9.1 fail to work

### ISSUE THREAD

**Issue by skykoradji** [Hashnode/mern-starter#342]
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/mern-starter/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/package.json.1225444790'

nyc package is too old?

**Comment by gmchaturvedi1** [comment]
+1

**Comment by mannyhenri** [comment]
@AndrewBestbier there seems to be a few issues with NPM installs, would you be open to take a look at it?

**Comment by AndrewBestbier** [comment]
Sure thing @mannyhenri

**Comment by mannyhenri** [comment]
@AndrewBestbier awesome, let me ask @fazlerocks to add you and if you have a PR I'll look into it

**Comment by mannyhenri** [comment]
Fixed with PR #367
