### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by MrChristofferson** [Hashnode/mern-starter#366]
Decide on `npm` vs `yarn` exclusively and include the lockfile in source control to eliminate tech debt.

**Comment by mannyhenri** [comment]
I'm all NPM, simply because it's the more mature one and has been improving a lot since yarn came out.

**Comment by mattlubner** [comment]
Haha, looks like I covered this in #367 as well!

We can totally switch between Yarn / NPM depending on what the community feels is the best decision. I think NPM is probably better for most, though, because of it's ubiquity.

**Comment by MrChristofferson** [comment]
Closing this, @mattlubner got `package-lock.json` in there 🎉
