### ISSUE TITLE
mern init mernApp

### ISSUE THREAD

**Issue by fatirjhon** [Hashnode/mern-starter#373]
module.js:538
    throw err;
    ^

Error: Cannot find module '../lib/commands/main.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Jhon\AppData\Roaming\npm\node_modules\mern-cli\bin\mern.js:3:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by alexandru-tomescu** [comment]
@fatirjhon more details please ? Do you pulled the last version ? Command ? Environment info ?

**Comment by ronwsg** [comment]
I face the same
Node v8.9.3
mern-cli@3.0.2
windows 10

C:\app> npm install -g mern-cli
C:\Users\xxxx\AppData\Roaming\npm\merng -> C:\Users\xxxx\AppData\Roaming\npm\node_modules\mern-cli\bin\merng.js
C:\Users\xxxx\AppData\Roaming\npm\mern -> C:\Users\xxxx\AppData\Roaming\npm\node_modules\mern-cli\bin\mern.js
+ mern-cli@3.0.2
added 28 packages in 3.131s

C:\app>mern init myApp
module.js:538
    throw err;
    ^

Error: Cannot find module '../lib/commands/main.js'
    at Function.Module._resolveFilename (module.js:536:15)
...

**Comment by vdhoangson** [comment]
same error on mac os

**Comment by decentraliser** [comment]
same error on bionic beaver

**Comment by MrChristofferson** [comment]
We've identified the problem and will be patching soon. A temporary work-around is to clone and run the `mern-starter` repository yourself. We'll let you know when this is resolved. Thanks for reporting 👍

**Comment by fatirjhon** [comment]
@alexandru-tomescu I just want to create mern project in CLI way, when installing `npm install -g mern-cli` there is no problem.

**Comment by mannyhenri** [comment]
Folks, just sent a fix to MERN-CLI and I've also backtracked the version to match our current roadmap so it's normal if you see version 2.4.1! But it should be working now!

**Comment by mannyhenri** [comment]
@fatirjhon @vdhoangson @ronwsg @decentraliser let me know if you see the error again but it should be fixed now.

**Comment by vdhoangson** [comment]
<img width="565" alt="screen shot 2018-06-06 at 9 52 44 pm" src="https://user-images.githubusercontent.com/4547214/41046122-ffe4df6e-69d3-11e8-99f9-d0568b03d477.png">

can't init new app

**Comment by mannyhenri** [comment]
@vdhoangson re-install to the latest version (V2.4.1) so either do `npm i -g mern-cli` to do a fresh reinstall or `npm uninstall -g mern-cli` and then the above command. This is the error before the update

**Comment by mannyhenri** [comment]
@vdhoangson You should be installing from this package: https://www.npmjs.com/package/mern-cli

**Comment by mannyhenri** [comment]
@vdhoangson just to be absolutely certain you can do `npm i -g mern-cli@2.4.1`

**Comment by vdhoangson** [comment]
@mannyhenri  i can install it. thank you

**Comment by fatirjhon** [comment]
@mannyhenri it works on @2.4.1 thank you so much dude !
