### ISSUE TITLE
help with commenting code

### ISSUE THREAD

**Issue by SOSANA** [Hashnode/mern-starter#39]
Hi guys,

noticed not a lot of comments regarding code to help explain. you guys open to commenting code?

**Comment by sandeeppanda92** [comment]
Sure. We are open to that. It'll be great if you can comment and send PRs.

**Comment by SOSANA** [comment]
Sure, thanks for considering this, might need your help on other aspects  :)

**Comment by SOSANA** [comment]
@sandeeppanda92 should I do a few pieces of code at a time for this? I am thinking of taking care of some of the shared code first. I wonder how far I should go with commenting. 

Any one else want to chime in?

**Comment by SOSANA** [comment]
@mayankchd thoughts?

**Comment by plankguy** [comment]
+1 i'd love see see comments!

**Comment by SOSANA** [comment]
@prank7 @carloscuatin @mayankchd I don't want to over due it but guess you guess you guys can chime in when I or someone else adds comments via pr, I can take a stab js files at a time but just wanted thoughts for this

**Comment by somus** [comment]
@SOSANA I've added a good amount of comments in v2 branch. If you think there can be more, feel free to send a PR.
