### ISSUE TITLE
Upgrading to webpack 4 breaks the mern-starter

### ISSUE THREAD

**Issue by JamesSingleton** [Hashnode/mern-starter#392]
When trying to upgrade to the latest version of dependencies (at least webpack) I get that `Field 'browser' doesn't contain a valid alias configuration`

Is there any progress being done to upgrade the dependencies to the latest versions? I know there is #344 but even that list is out of date.

**Comment by mannyhenri** [comment]
Yes we are working on all the updates related to dependencies, currently working on react router (v2.6)....
