### ISSUE TITLE
Error importing header / footer background image

### ISSUE THREAD

**Issue by sn17091004** [Hashnode/mern-starter#393]
Hi, 

I cloned this repo and running it locally. The background images for header and footer sections are not loaded and they failed. With the following errors 

1. (index):46 GET http://0.0.0.0:8000/bbaeb5f32b7042f0def39648a1d111b9.png 0 () 
2. Request URL: http://0.0.0.0:8000/bbaeb5f32b7042f0def39648a1d111b9.png -> Warning provisional headers are shown. 

Not able to find from google how to fix this. Any help will be appreciated. 

Thanks.

**Comment by sn17091004** [comment]
This solution fixed my issue. Please note : I had to do `ctrl+c` and then do `npm run start` again to make this work.

**Comment by yogesh27** [comment]
You had to do ctrl+c and the npm run start because you made changes in webpack.config.js file and I believe nodemon is not listening/watching to webpack changes.

**Comment by sn17091004** [comment]
Hi,

I am following this tutorial https://medium.com/@Keithweaver_/setting-up-mern-stack-on-aws-ec2-6dc599be4737 and trying to deploy this app.

However, I am stuck in this step pm2 start server.js -- --production . It is throwing error but there is no description of error / logs.

Have anyone deployed this app to EC2 with PM2 ? Can you please help in deploying this app ?

Or is there anything wrong with this command pm2 start server.js -- --production

Thanks,
