### ISSUE TITLE
this.props.history is undefined     Trying to access history object

### ISSUE THREAD

**Issue by 9gaurav** [Hashnode/mern-starter#395]
I am trying to create a login page. 
After verifying user credentials I would like to redirect the user to /home page.

I am struggling to understand how to handle redirection on server / client side.

1. First I tried to use history
But history is undefiend. 

```
handleLoginSubmit = (e) =>{

//TODO  auth code 

//if success
this.props.history.push('/home')

}
```

2.
Importing createHistory gave me access to history object.
But history.push would only change the url and it won't redirect the page.

```
import createHistory from 'history/createBrowserHistory'
const history = createHistory()
history.push('/home')
```

3. I thought it was because it was not in sync with react-router.
Hence followed solution stated on this page [https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md#third-party-code](url)
But no luck.

```
import { withRouter } from 'react-router'
export default withRouterconnect(mapStateToProps)(LoginPage);
```

I am really excited to use mern-starter for my project. 
But I would really appreciate if someone can help me understand routing and auth better. 
Thanks.

**Comment by 9gaurav** [comment]
Solved. My Bad.

React-Router 3.0.0+ uses the router and not history

`this.props.router.push('/some/path')`

Redirect Works.

**Comment by Aditya750793** [comment]
I'm using react router 6.4.0 doesnt work for me
