### ISSUE TITLE
Website is lacking pictures

### ISSUE THREAD

**Issue by koresar** [Hashnode/mern-starter#396]
Sorry for screenshots, it's the easiest way to report. Also, sorry doing that in this repo, couldn't find any other place.

![image](https://user-images.githubusercontent.com/1622575/45782799-4b149300-bca7-11e8-9c55-474d3b670316.png)

![image](https://user-images.githubusercontent.com/1622575/45782827-5ff12680-bca7-11e8-9086-cb4fcaf1ab84.png)

**Comment by mannyhenri** [comment]
Thanks for reporting this one, as soon as we're at version 3.0 we'll update the site which will fix this one!
