### ISSUE TITLE
Add nice warning if mongodb is not installed

### ISSUE THREAD

**Issue by tomaskikutis** [Hashnode/mern-starter#40]
I hit npm start and got long error message about failed server. I took some time to figure out that I need to install mongodb add it to path and have mongod running in other console window. All other tasks are run by npm, so I expected it would just work.

It the beggining it gave me a nice warning about not having git installed. It could do the same with mongodb.

**Comment by SOSANA** [comment]
@tomaskikutis do a pr for this :)

**Comment by tomaskikutis** [comment]
I don't know how to reply politely in this situation, but I'm not interested in this project enough to invest the amount of time a PR would take. This issue I've opened is as much as I can help. :)

**Comment by prank7** [comment]
We have mentioned this in quick setup part in README. However, I have added a [warning](https://github.com/Hashnode/mern-starter/commit/349022fa07e671e0e3a110e4c2f2c863e214b891 ) along with throwing error. Thanks @tomaskikutis and @SOSANA
