### ISSUE TITLE
Why need -g cross-env?

### ISSUE THREAD

**Issue by christiansakai** [Hashnode/mern-starter#41]
In `package.json` cross-env is already installed.  Why do we need to `npm install -g cross-env`?

**Comment by beaucharman** [comment]
We don't. Not sure why that is in the README, maybe someone is having an edge case issue if cross-env is not installed globally?
 
On that note, I propose that there are no global dependencies expect Node and MongoDB :D

**Comment by mayankchd** [comment]
Somebody was having a issue with that and installing it globally solved it but removed it from README for now!
