### ISSUE TITLE
Styles, pictures in component in isomorphic app

### ISSUE THREAD

**Issue by christiansakai** [Hashnode/mern-starter#43]
This boilerplate doesn't come with any css/scss/stylus/less or assets loader that will automatically read the file located in each component.  Example:
```
Footer.scss
Footer.js
logo.png
```

Is there any plan to make this configuration? This isn't as simple as people might think due to isomorphism.  Any pre-configuration will be great!

**Comment by somus** [comment]
Support for importing styles and images has been added in the latest commit(0e659da2e43de6ece5022738599fe786a73addec).
