### ISSUE TITLE
webpacking the server for production

### ISSUE THREAD

**Issue by dustinsanders** [Hashnode/mern-starter#48]
Is there any interest in using webpack on the server for production, as outlined [here](https://github.com/reactjs/react-router-tutorial/blob/start/lessons/13-server-rendering.md). If there is interest, I can submit a pull request.

**Comment by Ajar-Ajar** [comment]
+1 for compiling the server... 
At the moment, production build is using Babel-register hook which was not meant to be used in production...
@dustinsanders - the link you mentioned is broken

**Comment by prank7** [comment]
@dustinsanders sure it is. If you can submit a PR that would be great.

**Comment by prank7** [comment]
@Ajar-Ajar this is the right [link](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/13-server-rendering).

**Comment by prank7** [comment]
IMHO we should have a different webpack config file for server-side, which builds a '/build/server.build.js'. Is there a better way to do this?

**Comment by Ajar-Ajar** [comment]
@dustinsanders - thank you for the link, nice trick with the if-env script in the package.json to create a unified npm start rutine... the only thing I'm missing in this setup is that the server doesn't use es6 features like import that require a babel compilation. and suppose we do need to compile it, we will probably need to modify the folder structure to use both client and server under the dist folder...
@prank7 is webpack being used to compile the server as well? all the examples I came across so far had to do with the client only... have you tried it to compile the server before? interesting...

**Comment by prank7** [comment]
@Ajar-Ajar I haven't done it before but that is what this [link](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/13-server-rendering#server-rendering) is suggesting.

**Comment by somus** [comment]
If we are webpacking the server, css-modules-require-hook is not working. We have to figure out another way to inject css modules class names in the rendered html. After that, we can keep enable server webpacking again.

**Comment by carloscuatin** [comment]
👍

**Comment by lubien** [comment]
This react-router tutorial use this approach to get externals:
```js
  // keep node_module paths out of the bundle
  externals: fs.readdirSync(path.resolve(__dirname, 'node_modules')).concat([
    'react-dom/server', 'react/addons',
  ]).reduce(function (ext, mod) {
    ext[mod] = 'commonjs ' + mod
    return ext
  }, {}),
```
I've used it and got lots of problems (mostly with babel-polyfill). The solution was simply using [Morhaus/webpack-externals-plugin](https://github.com/Morhaus/webpack-externals-plugin).

I just wanted to share with you my experience. Hope this plugin could be helpful to v2.

[My webpack config for server](https://github.com/lubien/koa-react-redux-universal-boilerplate/blob/master/webpack.prod.server.js).

**Comment by somus** [comment]
Done in e7975db877536f1cd404c4123d47f92ebe0e8bc5.

@lubien Thanks for the suggestion. Added in 9aaf5a292764759d3ac8a440b8f015903a840162.
