### ISSUE TITLE
Incorrect data fetching pattern

### ISSUE THREAD

**Issue by rdiazv** [Hashnode/mern-starter#51]
According to [this article](https://facebook.github.io/react/tips/initial-ajax.html), each component should fetch the data it needs on `componentDidMount` method, so, for instance, it wouldn't be necessary for `PostDetailView` to do this when clicking on the root route link:

````javascript
handleLogoClick() {
  this.props.dispatch(Actions.fetchPosts());
}
````

`PostDetailView` shouldn't have to load data for `PostContainer`, in fact, it doesn't even have to know what data `PostContainer` needs, otherwise, every component that links to another would have to manually load data that's not relevant to itself, what's absolutely tedious and a nightmare to maintain.

The problem with this it's made clear doing this:
1. Open the app (ie, http://localhost:8000/)
2. Click on a post title (now the url it's /post/lorem-ipsum)
3. Reload the page
4. Click on the browser back button
5. Now the url it's http://localhost:8000/ and the post's list is empty

**Comment by prank7** [comment]
@rdiazv  Thanks for pointing that out, would be great if you could submit a PR.

**Comment by SOSANA** [comment]
@rdiazv you still working on this? if not can we tag "up for grabs" @prank7

**Comment by rdiazv** [comment]
@SOSANA no i'm not working on this
