### ISSUE TITLE
Please implement languages support with react-intl

### ISSUE THREAD

**Issue by Ajar-Ajar** [Hashnode/mern-starter#54]
Please implement languages support with react-intl
Vote +1 for this feature

**Comment by beaucharman** [comment]
+1

**Comment by spyhole** [comment]
+1

**Comment by marr** [comment]
+1

**Comment by joernroeder** [comment]
+1

**Comment by carloscuatin** [comment]
https://github.com/SUI-Components/rosetta use simple implementation, since react-intl involves the application with a new component, and it does not seem necessary this opinion?

**Comment by somus** [comment]
Done by @sirrodgepodge on #163 and #166.
