### ISSUE TITLE
KOA > Express

### ISSUE THREAD

**Issue by amcdnl** [Hashnode/mern-starter#59]
You should use KOA instead of Express.

See: https://github.com/expressjs/express/issues/2844

**Comment by prank7** [comment]
Sure Koa is awesome, we wanted to keep it simple and thus Express. @camerow forked mern and made [mern-starter-hapi](https://github.com/camerow/mern-starter-hapi). Would love to see if you replace Express with Koa.

**Comment by amcdnl** [comment]
Technically KOA is more simple than Express. Its just a middleware vs the kitchensink. ;) #justsayn
