### ISSUE TITLE
createBrowserHistory

### ISSUE THREAD

**Issue by sylvainlap** [Hashnode/mern-starter#62]
In client/index.js, there is a

`import createBrowserHistory from 'history/lib/createBrowserHistory';`

However, this is never used.

What is the purpose of this import ?

**Comment by SOSANA** [comment]
in 
client/index.js
```
import createBrowserHistory from 'history/lib/createBrowserHistory';

const store = configureStore(window.__INITIAL_STATE__);
const history = browserHistory;

render((
      <Provider store={store}>
        <Router history={history} routes={routes} />
      </Provider>
      )
     , document.getElementById('root'));
```

we assign a variable name history to the createBrowserHistory and than we pass it to our Router as shown above

**Comment by SOSANA** [comment]
@sandeeppanda92 feed back? can we close this issue?

**Comment by carloscuatin** [comment]
the target is to use createBrowserHistory If you are using the what is done in no time is imported browserHistory from react-router ??

**Comment by SOSANA** [comment]
@carloscuatin @sylvainlap ya this is interesting I got mixed up with ```import { Router, browserHistory, Route, IndexRoute, match } from 'react-router';```  :(

@sandeeppanda92 wondering why is this ?

**Comment by sandeeppanda92** [comment]
@sylvainlap @SOSANA @carloscuatin Removed `createBrowserHistory ` as we are no longer using it.
