### ISSUE TITLE
server side initialState

### ISSUE THREAD

**Issue by sylvainlap** [Hashnode/mern-starter#63]
For server side rendering, the initialState is set thanks to:

```
const initialState = { posts: [], post: {} };

const store = configureStore(initialState);
```

Wouldn't be better to set initalState to null, so that the initialState is handled by reducers ?

Moreover, as it is a boilerplate, most people won't have posts in their app, and this initialState is a little hidden in server code.

**Comment by somus** [comment]
Thank you for pointing out. We are making changes to file structure for v2 of MERN. I will fix this there. You can check out the roadmap discussion for v2 at #146.

**Comment by somus** [comment]
Done on v2 branch.
