### ISSUE TITLE
Can we make Mongo optional?

### ISSUE THREAD

**Issue by antigirl** [Hashnode/mern-starter#64]
Hey Guys,
Would it be possible to add some questions when scaffolding, similar to yeomen?
It would be amazing to have an isomorphic start point with minimal dependencies.

Thanks

**Comment by sandeeppanda92** [comment]
Yes, we are working on a roadmap and will soon have various options in the CLI. You can participate in the discussion [here](https://hashnode.com/post/working-on-mern-cli-opinions-cikv8y4x500e4i4538qus6d6m).

And if we make Mongo optional, it won't be MERN anymore. You can always fork this repo and replace Mongo with something else.

**Comment by SOSANA** [comment]
this repo is called MERN stack { mongodb, express, react, node.js }

maybe make a branch called MERD { mongodb, express, react, database }
:)

**Comment by antigirl** [comment]
fair point fellas.
