### ISSUE TITLE
Couldn't find preset es2015-loose

### ISSUE THREAD

**Issue by pomeo** [Hashnode/mern-starter#76]
`node -v`
`v5.5.0`
`npm -v`
`3.3.12`

`git clone git@github.com:Hashnode/mern-starter.git`
`npm install`
`npm run build`

> ERROR in ./~/redux-devtools-log-monitor/lib/index.js
> Module build failed: Error: Couldn't find preset "es2015-loose" relative to directory "node_modules/redux-devtools-log-monitor"

**Comment by mayankchd** [comment]
@carloscuatin

**Comment by carloscuatin** [comment]
exactly like this there are several errors in the code I tratatando to fix more to avoid such errors
