### ISSUE TITLE
Server rendering with material-ui components

### ISSUE THREAD

**Issue by lorix-lpan** [Hashnode/mern-starter#84]
Hi, when I add material design components provided from the material-ui library to my project, server rendering fails and it prints the following to the console.
```
Server-side React render was discarded. Make sure that your initial render does not contain any client-side code.
```

According to [the material-ui doc](http://www.material-ui.com/#/get-started/server-rendering), I tried to add
```javascript
app.use(function(req, res, next) {
  GLOBAL.navigator = {
    userAgent: req.headers['user-agent']
  }
  next();
});
```
to /server/server.js.
However, it still does not work.

Can you please provide a set of instructions to resolve this issue?

Thank you very much

**Comment by carloscuatin** [comment]
Solution problem with material-ui is:

#### Install babel-plugin-transformer-decorators-legacy and babel-preset-stage-1
```sh
$ npm install --save-dev babel-plugin-transform-decorators-legacy
$ npm install --save-dev babel-preset-stage-1
```

#### File `.babelrc`

```json
{
  "presets": ["react", "es2015", "stage-1"],
  "plugins": ["transform-decorators-legacy"]
}
```
#### File `shared/container/App.js`

```js
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';

import MyRawTheme from './configTheme';
import getMuiTheme from 'material-ui/lib/styles/getMuiTheme';
import themeDecorator from 'material-ui/lib/styles/theme-decorator';

@themeDecorator(getMuiTheme(MyRawTheme, { userAgent: 'all' }))
class App extends Component {
  constructor(props, context) {
    super(props, context);
  }

  render() {
    return (
      <div>
        { this.props.children }
      </div>
    );
  }
}

App.propTypes = {
  children: PropTypes.node.isRequired
};

export default connect()(App);
```

I hope this solves your problem at least to me I fix me and Material-ui have regular running smoothly rendering

**Comment by lorix-lpan** [comment]
Thank you so much for your help. Server rendering now works like a charm.

**Comment by lorix-lpan** [comment]
Hi, server rendering works now but everything becomes significantly slow :P . There is a latency between the user action and the response of the app. For example, when I type a letter, it takes like two seconds to display it on the input field.

**Comment by lorix-lpan** [comment]
@carloscuatin Hey Carlos, as you can see here: https://github.com/lorix-lpan/mern-starter, the latency is quite obvious. Is there a way to resolve this? 

Thanks again

**Comment by carloscuatin** [comment]
@lorix-lpan latency produced by every `user-agent: all`, I'm looking for a solution

**Comment by lorix-lpan** [comment]
Thank you very much!

**Comment by lorix-lpan** [comment]
Hey @carloscuatin, I rolled back to version 0.14.2 and the latency disappears with exactly the same code. I think it is an issue with material-ui. Thanks again for your help

**Comment by carloscuatin** [comment]
@lorix-lpan if exactly that would indeed discuss the issue opened a repository-ui material as this is an error in the autoprefixer
