### ISSUE TITLE
test:server failure

### ISSUE THREAD

**Issue by jonsrose** [Hashnode/mern-starter#86]
I used the mern cli tool to create  a new app and see these errors when i run the test:server tests

GET /api/getPosts
    ✓ Should correctly give number of Posts (1539ms)

  GET /api/getPost
    ✓ Should send correct data when queried against a title (615ms)

  POST /api/addPost
    1) Should send correctly add a post

  POST /api/deletePost
    2) "before each" hook: connect and add one Post entry
    3) "after each" hook for "Should connect and delete a post"

  2 passing (12s)
  3 failing

  1) POST /api/addPost Should send correctly add a post:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) POST /api/deletePost "before each" hook: connect and add one Post entry:
     Uncaught TypeError: Cannot read property 'name' of null
      at post.spec.js:118:18
      at Query.<anonymous> (node_modules/mongoose/lib/query.js:2149:28)
      at node_modules/mongoose/node_modules/kareem/index.js:177:19
      at node_modules/mongoose/node_modules/kareem/index.js:109:16

  3) POST /api/deletePost "after each" hook for "Should connect and delete a post":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by carloscuatin** [comment]
I find it very strange just upgraded and run test: server and there is no problem could you please provide more information or have modified the test

![test](http://i.imgur.com/BqGCKrM.png)

**Comment by mayankchd** [comment]
All tests are passing for me too.. Check again and let me know!

**Comment by jonsrose** [comment]
Im seeing different issue now - i think there might be an issue with the computer as it is acting really slow, do you know how long should it take to run npm install in a new mern project? it is taking me about 3 and a half minutes which seems really long

GET /api/getPosts
    1) Should correctly give number of Posts

  GET /api/getPost
    ✓ Should send correct data when queried against a title (529ms)

  POST /api/addPost
    ✓ Should send correctly add a post (878ms)

  POST /api/deletePost
webpack built b60656cce612f1addf89 in 6195ms
    ✓ Should connect and delete a post


  3 passing (6s)
  1 failing

  1) GET /api/getPosts Should correctly give number of Posts:

      Uncaught AssertionError: expected 2 to equal 1
      + expected - actual

      -2
      +1

**Comment by carloscuatin** [comment]
tests run again the fault is in your pc run them when I vuelvelo do and fixed pass, were attentive you warn us

**Comment by WillHearn** [comment]
I believe there is an issue with the deletePost test - that while it reports successful it does so without running

expect(post).to.equal(null);

What I believe is happening is the afterEach() cleanup is being called prior to executing deletePost in the post.controller.js

and the test is falling through without reporting a failure.  
I have yet to understand why this is though

**Comment by WillHearn** [comment]
I believe the problem is that the 'done' state is not passed into the deletePost test

it('Should connect and delete a post', function () {

should be

it('Should connect and delete a post', function (done) {

I'll raise a pull request for review
