### ISSUE TITLE
Add GraphQL to mern-starter

### ISSUE THREAD

**Issue by prank7** [Hashnode/mern-starter#88]

**Comment by carloscuatin** [comment]
add graphql, particularly redux would have to change for relay and relay the truth is not doing very well in applications isomorphic

**Comment by mayankchd** [comment]
Yup. We are thinking of adding GraphQL in a seperate repository.

**Comment by carloscuatin** [comment]
they will with relay I imagine?

**Comment by mayankchd** [comment]
Yup! @carloscuatin  are you facing this issue https://hashnode.com/post/error-occurred-after-npm-run-build-in-mern-starter-cilb1tw7i004utw53j4rh3bww ? I'm not able to reproduce it.

**Comment by carloscuatin** [comment]
yes, i'm reproduce in windows

**Comment by SOSANA** [comment]
@carloscuatin @mayankchd I was able to successfully run tests in windows, only thing I noticed was spelling mistake so did a pr #91

**Comment by SOSANA** [comment]
@mayankchd 1+ for seperate repo :+1:

**Comment by Ajar-Ajar** [comment]
any news on the graphql support? 
Is there another repo / fork that implements it yet?

**Comment by somus** [comment]
We are planning to work on MERN v2 starting today. After that, we will work on the advanced version of MERN which will include graphql and redux saga.
