### ISSUE TITLE
Add SCSS or PostCSS or both with CSS Modules

### ISSUE THREAD

**Issue by prank7** [Hashnode/mern-starter#89]

**Comment by SOSANA** [comment]
This should only be applied when scaffolding app correct? not everyone uses scss

**Comment by evansendra** [comment]
Right now #50 allows to use SCSS... @SOSANA doing it while scaffolding is an interesting idea. Is there already a scaffolding structure in place?

**Comment by stephan281094** [comment]
Wouldn't it be better to make SCSS optional? Maybe as a flag or option within mern-cli?

**Comment by evansendra** [comment]
That's currently suggested in the comments of #50 not sure where the maintainers are on this

**Comment by prank7** [comment]
@evansendra @stephan281094 @SOSANA Yes, not every one uses SCSS and so we shouldn't really put it in main starter app. I think we can just add loader for scss in webpack so that it CSS and SCSS files can be bundled. We should also keep the CSS for starter app in .css format. 

I think @evansendra has done a great job in #50. Just one thing to mention there is that SCSS folder should not sit in root directory, may be` /static/scss` is a better option. What say @evansendra @stephan281094  @SOSANA ?

**Comment by carloscuatin** [comment]
I think it's best to leave the sass-loader in webpack and explain the project in the future with mern-cli should leave it as an option

**Comment by stephan281094** [comment]
@prank7 Thanks for asking for my opinion. I agree with your suggestion. Putting the SCSS folder next to the CSS folder in `/static` seems like a more logical place. However, having two different CSS files (in this case `public.min.css` and `app.min.css` seems confusing.

**Comment by evansendra** [comment]
Agreed with the above...leave SCSS in webpack configs and as for location `/static` seems logical.  Having `public.min.css` and `app.min.css` assumes someone would use both scss and vanilla css, but if we assume they'll use one exclusively we can always resolve to `public.min.css`...if this sounds good I'll modify it this way or others can hop in if desired

**Comment by prank7** [comment]
Sure @evansendra. Please go ahead.

**Comment by weslleyaraujo** [comment]
would be nice to have this as an option, btw lots of people are migrating from SCSS/SASS to postcss only... which I think could also be an option :+1:

**Comment by Ajar-Ajar** [comment]
I think ideally sass needs to be implemented with CSS Modules support #115 
++1 for implementing Sass
:)

**Comment by Ajar-Ajar** [comment]
@weslleyaraujo I've been checking out postcss and I must say I agree with you. 
It looks like postcss is picking up in momentum and it blends into the webpack and CSS Modules much more smoothly. it has all the advantages sass gives you and tones more, and it's all in javascript!
So I have to vote for postcss and advise everyone here to check it out in depth.

**Comment by SOSANA** [comment]
1+ @Ajar-Ajar

**Comment by weslleyaraujo** [comment]
@Ajar-Ajar definitely! you got lots of advantages by using both together, webpack plays real nice with postcss..

The most useful features from SASS (variables, nesting, mixins) are all available by using postcss, I have played with it just a bit [here](https://github.com/weslleyaraujo/pokedux/blob/master/webpack.config.babel.js) and as you can see, the configuration is minimal :)

**Comment by SOSANA** [comment]
Hey all, for those of you interested in checking out postcss found this playlist tutorial on YouTube while eating lunch the other day thought it explained it pretty well https://m.youtube.com/playlist?list=PLLnpHn493BHFvjZzyYrQP0RTsG-Al7j9m

**Comment by weslleyaraujo** [comment]
hey guys, are any work in progress on that?
I am willing to write a PR for postcss support, just to check if it will really make sense for the project...

or as far I could understand: **we could have a dynamic/optional way to choose between scss support/postcss and so on..**

**Comment by carloscuatin** [comment]
use radium ? and css-modules for css globals ?

**Comment by somus** [comment]
@carloscuatin I'm not sure radium is something which we want. I've never been comfortable writing css using js. For css-modules support, we can use webpack's css-loader.

**Comment by carloscuatin** [comment]
I say this because this gives great scope when performing components

**Comment by somus** [comment]
I've added postcss with css-modules enabled to v2 branch (510101f).
