### ISSUE TITLE
mern-starter not following eslint airbnb

### ISSUE THREAD

**Issue by SOSANA** [Hashnode/mern-starter#92]
Hi Guys,

I am using the default airbnb linting style in my atom editor with jcsc plugin that pulls our eslint file and applys errors etc.

I noticed that we aren't exactly following this. 

Here are some examples that my ide shows errors for correcting...

require padding new lines after blocks - missing newline after block
require space after keywords - one space required eg "if" keyword
maximum line length - line must be at most 100 characters
require trailing comma - missing comma before closing bracket

Should we fix this? or am I missing something?

**Comment by KSMorozov** [comment]
@SOSANA i found some eslint errors myself but the one thing i notice in urs issue right of the bat that **max-len rule overwritten** in mern starter .eslintrc file to 180 chars
`"max-len": [1, 180, 4],`
so its reasonable to assume that urs .eslintrc somehow not recognized if u'r getting this error

**Comment by KSMorozov** [comment]
While we'r at eslint rules may someone please clarify how it was achieved that eslint not spitting consistent-return error in blocks like
```
export function getPosts(req, res) {
  Post.find().sort('-dateAdded').exec((err, posts) => {
    if (err) {
      return res.status(500).send(err);
    }
    res.json({ posts });
  });
}
```
**in**
> server/controllers/post.controller.js

**Comment by SOSANA** [comment]
@KSMorozov using atom linter + jscs plugin. Hmm this is strange, it should at least pick up our max char per line. I don't suppose your using atom ide? you ever hear of jscs? check it out [here](http://jscs.info/), wondering now how I can get it to work

**Comment by SOSANA** [comment]
@KSMorozov what errors are you getting? want to make sure max char line is my only problem.

here is what errrors I am getting...
require padding new lines after blocks - missing newline after block
require space after keywords - one space required eg "if" keyword
maximum line length - line must be at most 100 characters
require trailing comma - missing comma before closing bracket

**Comment by KSMorozov** [comment]
@SOSANA it was smth about **jsx-closing-bracket-location** 

 ```
 render() {
    return (
      <div>
        <Header onClick={this.handleClick} />
        <div className="container">
          <PostCreateView addPost={this.add}
            showAddPost={this.state.showAddPost}
            />
          <PostListView posts={this.props.posts}/>
        </div>
        <Footer />
      </div>
    );
  }
```

**in**
> shared/container/PostDetailView/PostDetailView.jsx

i can tell for sure that maximum line length is problem on ur end, it seems like ur .eslintrc dosent extending air-bnb config.
Btw i am using atom-nuclide not familiar with jscs, BUT from what i see at their landing page http://jscs.info/ u might using --preset airbnb **but u might actually should you local .eslintrc WHICH in turn extends airbnb rules and override some of them!**

**Comment by SOSANA** [comment]
Hey I am going to close this issue is a problem with my linter.

jscs and eslint two different projects, eslint doesn’t read jscs config and vice versa.

going to install a popular eslinter for my atom ide and see if errors still arise...

Thanks @KSMorozov for your help

**Comment by KSMorozov** [comment]
@SOSANA Good luck at troubleshooting issues!
