### ISSUE TITLE
Cannot read property map of undefined

### ISSUE THREAD

**Issue by cmckni3** [Hashnode/mern-starter#94]
```
Warning: Failed propType: Required prop `posts` was not specified in `PostContainer`. Check the render method of `Connect(PostContainer)`.warning @ warning.js?0260:45
Warning: Failed propType: Required prop `posts` was not specified in `PostListView`. Check the render method of `Connect(PostListView)`.warning @ warning.js?0260:45
Uncaught TypeError: Cannot read property 'map' of undefined localhost/:29
```

![image](https://cloud.githubusercontent.com/assets/735717/13507985/c63fedee-e14a-11e5-915b-00a286d62562.png)

**Comment by carloscuatin** [comment]
You could give me a little more context I can no longer reproduce the error, prove on Windows, Mac, Linux and the project goes well stay tuned

**Comment by cmckni3** [comment]
I am running Mac OS X El Capitan. I installed mern-cli and created a new project. I am running node.js 4.3.1 and npm 2.14.12. See commands below.

```bash
npm i -g mern-cli
mern foobar
cd foobar
npm i
npm start
```

**Comment by cmckni3** [comment]
I can confirm everything is working now including devtools. Thanks!

**Comment by cmckni3** [comment]
Just a little extra information. I was having trouble when using fcadd5fe29c2dbe8ad0209bcf0cefbd5eccc0cde

**Comment by carloscuatin** [comment]
:+1: @cmckni3

**Comment by daminufe** [comment]
Same problem here using the mern-cli

``` npm install -g mern-cli
    mern init myApp
    cd myApp
    npm install
    npm start```

Node: v6.5.0
NPM: 3.10.3
