### ISSUE TITLE
wtf is this sidebar thing?

### ISSUE THREAD

**Issue by cleechtech** [Hashnode/mern-starter#95]
I launched the starter app and this came up. What is it and why is it there? If you explain me I will happily submit a PR to the documentation!

![screen shot 2016-03-05 at 2 34 08 pm](https://cloud.githubusercontent.com/assets/3578908/13550994/6b681450-e2df-11e5-8b64-8d0f8602b2ad.png)

**Comment by carloscuatin** [comment]
The sidebar that you look there are devtools redux and serve to observe how the actions in addition to the results of the shoot, that would be great in the documentacón put it as hidden and changes posision

### commands 

* [x] hide redux-devtools `ctrl + h`
* [x] move redux-devtools `ctrl + w`

![devtools](http://g.recordit.co/Mhrq4NCxWD.gif)

**Comment by cleechtech** [comment]
PR submitted, along with some notes on file structure to README.md #96
