### ISSUE TITLE
Use redux-saga instead of redux-thunk

### ISSUE THREAD

**Issue by kerwin** [Hashnode/mern-starter#97]
How about this?

**Comment by prank7** [comment]
@kerwin I have heard good things about redux-saga, I haven't tried it yet though. Would be great if you can send a PR for this.

**Comment by SOSANA** [comment]
@kerwin why this is a better solution?

**Comment by somus** [comment]
As @jforaker pointed out in #106, redux saga is quite complex and not suitable for beginners. For advanced users who needs redux saga, we have plans to create a separate project.
