### ISSUE TITLE
Error upon initializing

### ISSUE THREAD

**Issue by sirrodgepodge** [Hashnode/mern-starter#98]
Love what you guys have done here.

Getting these three errors in browser console when the following is run:
npm install -g mern-cli
mern test
cd test
npm install
npm start

-Required prop `posts` was not specified in `PostContainer`. Check the render method of `Connect(PostContainer)`.
-Required prop `posts` was not specified in `PostListView`. Check the render method of `Connect(PostListView)`.
-Cannot read property 'map' of undefined

OSX version: 10.10.5
node version: v4.2.1
npm version: 2.14.7

**Comment by sirrodgepodge** [comment]
I'm digging into this a bit, looks like the issue must be happening in either "dispatch" or "applyMiddleware".

Somehow dispatch is not yielding a promise in the fetchComponentData function in '/server/util/fetchData.js'.

If you console.log " dispatch(need(params))" here it does not look like this is yielding a promise.

````
const promises = needs.map(need => dispatch(need(params)));
````

**Comment by mayankchd** [comment]
Working fine on my OSX v10.11.3 (15D21). Make sure your mongoDB is up and runnning.

**Comment by sirrodgepodge** [comment]
It's up and running for sure and contains the "ExampleData.js" documents (confirmed via CLI).

I am still on Yosemite and you're on El Capitan (work laptop, they're not ready for upgrade yet), not sure how this could be making a difference in this case though...

**Comment by carloscuatin** [comment]
@sirrodgepodge enter in `http://localhost:8000/api/getPosts` and take a screenshot

**Comment by sirrodgepodge** [comment]
I switched the port in "config.js" to 8080, here is teh screenshot
![screenshot 2016-03-14 11 35 57](https://cloud.githubusercontent.com/assets/7177292/13749727/05cd5b0e-e9d9-11e5-94e2-da3c4eb5e636.png)

**Comment by carloscuatin** [comment]
@sirrodgepodge run command

`npm run slate`

as it effectively is mongodb running and is not the problem

**Comment by SOSANA** [comment]
@sirrodgepodge delete your node_modules folder and npm install again.

**Comment by carloscuatin** [comment]
@SOSANA in mern-starter we have the script that performs this in one command 

![img](http://i.imgur.com/rwxJTbU.png)

**Comment by SOSANA** [comment]
@carloscuatin nice screen shot buddy, ya either way works :+1:

**Comment by carloscuatin** [comment]
I think we're going to have to use docker to have a development environment and avoid us like this whole world of problems with compatibility

they think of this @mayankchd @prank7 @SOSANA

**Comment by SOSANA** [comment]
@carloscuatin I like the idea of docker, but to be fair I jump from windows, mac, to linux vm, depends which is closer to me to code with :+1:

**Comment by sirrodgepodge** [comment]
Still doesn't work after doing this and deleting the 2 mongo documents (so they can be re-added) for good measure :(.

I'll say it did work on my friend's computer two days ago and he was on El Capitan, that's the only version difference we have that I know of.

**Comment by carloscuatin** [comment]
@sirrodgepodge Let me try to reproduce the error to collaborate

**Comment by sirrodgepodge** [comment]
okay, if I have sometime today I'll try digging into it myself

**Comment by sirrodgepodge** [comment]
k so, my best guess is that it has something to do react-router's "match" function, which it looks like they've made some changes to recently:
https://github.com/reactjs/react-router/blob/master/CHANGES.md

**Comment by sirrodgepodge** [comment]
So turns out that while there was incorrect error logging shrouding this issue in OSX Yosemite, the problem was actually that the base route referenced in "actions.js" was hardcoded to be "8000" and did not update when the "port" property in "server/config.js" got updated, fixed in a PR here:

https://github.com/Hashnode/mern-starter/pull/105

:)

**Comment by prank7** [comment]
Thanks @sirrodgepodge
